<?php ?>
<? //require_once realpath(dirname(__FILE__).'/inc/config.php'); ?>
<? require_once ('AlgorithmsIO/config.php'); ?>
<? 
//$wizard_height="500px";
global $GLOBALS;
//$GLOBALS["htmllinktags"] = <<<EOS
$htmllinktags = <<<EOS
<link rel="stylesheet" href="/css/dashboard.css">
<!-- Bootstrap CSS Toolkit styles -->
<link rel="stylesheet" href="/css/fileupload/bootstrap.min.css">
<!-- Bootstrap styles for responsive website layout, supporting different screen sizes -->
<link rel="stylesheet" href="/css/fileupload/bootstrap-responsive.min.css">
<!-- Bootstrap CSS fixes for IE6 -->
<!--[if lt IE 7]><link rel="stylesheet" href="/css/fileupload/bootstrap-ie6.min.css"><![endif]-->
<!-- CSS to style the file input field as button and adjust the Bootstrap progress bars -->
<link rel="stylesheet" href="/css/fileupload/jquery.fileupload-ui.css">
<!-- Shim to make HTML5 elements usable in older Internet Explorer versions -->
<!--[if lt IE 9]><script src="/js/html5.js"></script><![endif]-->

<link rel="stylesheet" type="text/css" href="/css/flexigrid/flexigrid.pack.css" />
<link rel="stylesheet" type="text/css" href="/css/market.css" />
EOS;
#<!--[if lt IE 9]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->

$javascript = <<<EOS
<script src="/js/bootstrap-tab.js"></script>
EOS;

echo pageheader(array(
	"htmllinktags"	=>$htmllinktags,
	"javascript"	=>$javascript,
        "nav_tab"       =>"visualizations",    
        "view"          =>$this    
)); 

$dashboard_warning = "";

// Cycle through the localization messages to see if any warnings should be issued about credits - MRR 20120614
foreach ($this->localization->dashboard->notices->credits as $cred_notice) {
	$attribs = $cred_notice->attributes();
	$credits = $this->authentication->credits();
	if(($credits >= $attribs["min"]) && ($credits <= $attribs["max"])) {
		$dashboard_warning = "".$cred_notice;
	}
}

?>
<SCRIPT src="/js/algo.js"></script>
<SCRIPT>
$(function (){
	$('#dashboardTabs').tab('show');
	$('#dashboardTabs a:first').tab('show');
	//$('#dashboardWarning').fadeIn('slow');
});
</SCRIPT>
<div id="holder" style="min-height: 600px">
<div id="dashboard_tabs">

<ul class="nav nav-tabs" id="dashboardTabs">
<? if ($this->security->canRead("Market_DataSources_Browse")) { ?>
  <li><a href="#market_datasources_browse_tab" data-toggle="tab">Browse</a></li>
<? } ?>
<? if ($this->security->canRead("Market_DataSources_Search")) { ?>
  <li><a href="#market_datasources_search_tab" data-toggle="tab">Search</a></li>
<? } ?>
    <!--
<? if ($this->security->canRead("Market_DataSources_Details")) { ?>
  <li><a href="#market_datasources_details_tab" data-toggle="tab">Details</a></li>
<? } ?>
  -->
</ul>


<div class="tab-content" zid="dashboard_tabs">
  <div class="tab-pane fade active" id="market_datasources_browse_tab" style="min-height: 500px;">

<? if ($this->security->canRead("Market_DataSources_Browse")) { ?>
<? require_once("MarketItemLoop.php"); ?>


<BR><BR>
<? } ?>
  </div>
  <div class="tab-pane fade" id="market_datasources_search_tab" style="min-height: 500px;">
<!-- *************************** BEGIN Search ********************************************* -->
<? if ($this->security->canRead("Market_DataSources_Search")) { 
    echo "Show search form and results"; 
} ?>
<!-- *************************** END Search ********************************************* -->
  </div>
  <div class="tab-pane fade" id="market_datasources_details_tab" style="min-height: 500px;">
<!-- *************************** BEGIN Details ********************************************* -->
<? if ($this->security->canRead("Market_DataSources_Details")) { 
    echo "Show details on selected item...";
} ?>
<!-- *************************** END Details ********************************************* -->
  </div>

</div>
</div> <!-- END dashboard_tabs -->
</div> <!-- END holder -->

<BR><BR>
<? echo pagefooter(); ?>
