<? // login/index.phtml ?>
<? //echo $this->form ?>

  <!-- header ends -->
  <!-- body starts -->
  <div class="body-outer">
    <div class="body">
    <div class="loginbody">
    <h1>Error Page Not Found</h1>

    <form action="/signup/aa" method="post">
        <div class="loginbox">
            <div class="form">
                <div class="row">
                        <div class="cl"></div>
                <div class="cl"></div>
            </div>
            <div class="row">
                <div class="cl"></div>
            </div>
            <div class="row2">
            <div class="cl"></div>                                                                                           
        </div>                                                                                                           
    </form>

     </div>
     <div class="newregister">
     </div>
     <div class="cl"></div>
     </div>
     </div>
      <div class="cl"></div>
    </div>
  </div>
  <!-- body ends -->
  <!-- footer starts -->
