<?php ?>
<? //require_once realpath(dirname(__FILE__).'/inc/config.php'); ?>
<? require_once ('AlgorithmsIO/config.php'); ?>
<? 
//$wizard_height="500px";
global $GLOBALS;

$htmllinktags = <<<EOS
<!-- Shim to make HTML5 elements usable in older Internet Explorer versions -->
<!--[if lt IE 9]><script src="/js/html5.js"></script><![endif]-->
<link rel="stylesheet" type="text/css" href="/bootstrap/css/bootstrap.css" />
<link rel="stylesheet" type="text/css" href="/css/flexigrid/flexigrid.pack.css" />
<link rel="stylesheet" href="/js/codemirror/codemirror.css">

<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.9.0.custom.css" />
<link rel="stylesheet" type="text/css" href="/css/layouts/viside_layout.css" />
EOS;
#<!--[if lt IE 9]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->

$API_JS = $this->API_URL."Jssdk/?authToken=".$this->token;
$javascript = <<<EOS
<!-- BEGIN: Layout Stuff -->   
<script type="text/javascript" src="/js/jquery.layout-latest.js"></script>
<script type="text/javascript" src="/js/jquery.layout.resizePaneAccordions-1.0.js"></script>
<script type="text/javascript" src="/js/jquery-layout-debug.js"></script>
<!-- END: Layout Stuff -->   

<script type="text/javascript" src="$API_JS"></script> 
<script type="text/javascript" src="/js/tiny_mce/jquery.tinymce.js"></script>
<script type="text/javascript" src="/bootstrap/js/bootstrap.js"></script>     
<script type="text/javascript" src="/js/bootstrap-tab.js"></script>
<script type="text/javascript" src="/js/jquery.jstree/jquery.jstree.js"></script>
<script type="text/javascript" src="/js/algo.js"></script>
<script type="text/javascript" src="/js/codemirror/codemirror.js"></script>
<script type="text/javascript" src="/js/codemirror/mode/javascript/javascript.js"></script>
<script type="text/javascript" src="/js/AlgorithmIDE.js"></script>
<script type="text/javascript" src="/js/jquery.timeago.js"></script>
EOS;

echo pageheader(array(
	"htmllinktags"	=>$htmllinktags,
	"javascript"	=>$javascript,
        "body_css"      =>"max", // Break out of the template width bindings
        "nav_tab"       =>"algorithms",    
        "view"          =>$this,
        "skip_body"     =>true,
        "header_off"    =>true,
)); 

$headerhack = getHeaderNav(array(
	"htmllinktags"	=>$htmllinktags,
	"javascript"	=>$javascript,
        "body_css"      =>"max", // Break out of the template width bindings
        "nav_tab"       =>"algorithms",    
        "view"          =>$this,
        "skip_body"     =>true,
        //"header_off"    =>true,
)); 

if (isset($_REQUEST['algorithm_id'])) {
    $algoid = $_REQUEST['algorithm_id'];
} else {
    $algoid ='';
}
?>
<SCRIPT>
<? if($algoid) {
    echo "var myIDE = new algorithmIDE($algoid);\n";
    echo "myIDE.retrieve();\n";
} else {
    echo "var myIDE = new algorithmIDE();\n";
    //echo "var myIDE = new algorithmIDE(null);\n";
}?>

$(function (){
    $('#div_datasources_list').hide();
    $('#div_algorithm_properties').hide();
    $('#div_inputparams_list').hide();
    $('#div_outputparams_list').hide();
    $('#div_algorithm_name').click(function(){
        showWizardPopup($("#div_algorithm_properties"));
        validateAlgorithmProperties();
    });
    $('#button_edit_inputparams').click(function(){
        showWizardPopup($('#div_inputparams_list'));
    });
    $('#button_edit_outputparams').click(function(){
        showWizardPopup($('#div_outputparams_list'));
    });    
    $('#outputparams_title').click(function(){
        showWizardPopup($('#div_outputparams_list'));
    });
    
    <? if(!isset($_REQUEST["algorithm_id"])) {
            echo "showWizardPopup(\$(div_algorithm_properties));";
    }?>
            
//    $( "#main_tabs" ).tabs({
//        select: refreshEditors
//    });   
    $( "#properties_tabs" ).tabs({
        //select: refreshEditors
    });  
});

</SCRIPT>

<!-- BEGIN Layout Test -->
<div class="ui-layout-west">
	<div class="header">User Settings</div>

	<div class="subhead">Settings Specified by the User</div>

<!--	<h3 class="ui-widget-header">East Pane</h3> -->

	<div class="ui-layout-content" style="height: 90%;">
	
                    <div id="accordion1" class="basic">
                        <h3><a href="#"><?=$this->localization->Algorithm->IDE->UserSettings->Title; ?></a></h3>
                        <div id="usersettings_container" zstyle="border: 1px solid red; position: relative; height: 100px;">
                            <div id="usersettings"></div>
                        </div>

			<h3><a href="#"><?=$this->localization->IDE->Libraries->LibraryTitletext; ?></a></h3>
                        <div id="somethingelse_container" class="well">
                            <div id="somethingelse"></div>
                        </div>
                        
                    </div>
        </div>

	<div class="footer">Automatically positioned footer</div>

</div>

<div class="ui-layout-east" style="height: 100%; display: none;">
	<div class="header">Resources</div>

	<div class="subhead">Resources for this Algorithm</div>

<!--	<h3 class="ui-widget-header">East Pane</h3> -->

	<div class="ui-layout-content" style="height: 90%;">
	
                    <div id="accordion2" class="basic">
                        <h3><a href="#"><?=$this->localization->IDE->Libraries->InputParamsTitletext; ?></a></h3>
                        <div id="inputparams_container" zstyle="border: 1px solid red; position: relative; height: 100px;">
                            <div id="inputparams"></div>
                            <button id="button_edit_inputparams" style="margin-top: 10px;">Modify Parameters</button>
                        </div>

			<h3><a href="#"><?=$this->localization->IDE->Libraries->LibraryTitletext; ?></a></h3>
                        <div id="library_container" class="well">
                            <div id="libraries"></div>
                        </div>
                        
			<h3><a href="#"><?=$this->localization->IDE->Libraries->OutputParamsTitletext; ?></a></h3>
                        <div id="outputparams_container">
                            <div id="outputparams"></div>
                            <button id="button_edit_outputparams" style="margin-top: 10px;">Modify Parameters</button>                            
                        </div>
		</div>
                <!-- <h4 class="ui-widget-content ui-state-hover">Accordion inside DIV.ui-layout-content</h4> -->

        </div>
</div>


<div class="ui-layout-north">
    <?
    echo $headerhack; 
    echo "</div>"; // Closes layout div
    ?>
</div>

<div id="mainContent">
	<!-- DIVs for the INNER LAYOUT -->

	<div class="ui-layout-center">
            <h3 id="div_algorithm_name" class="header"><span id="algorithm_name">Algorithm Title</span><a href="javascript:void(0);" onclick="" style="position: relative; top: -5px; float: right;"><img src="/images/glyphicons/glyphicons_030_pencil_white.png" class="button-general-icon"></a></h3>
            
            <div id="main_tabs">
                <!--
                <ul>
                    <li><a href="#CodeEditor">Javascript</a></li>
                    <li><a href="#HTMLEditor">HTML</a></li>
                    <li><a href="#CSSEditor">CSS</a></li>
                </ul>
                -->
                <div class="btn-group" style="margin-top: 10px; margin-left: 10px;">
                  <a id="dropdown_language_a" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#">
                    <span id="dropdown_language">R</span>
                    <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu" id="dropdown_language_list" class="dropdown-menu">
                      <LI>R</LI>
                      <LI>Java</LI>
                      <LI>PHP</LI>
                      <LI>Perl</LI>
                      <LI>Python</LI>
                      <LI>Haskell</LI>
                  </ul>
                </div>
                <SCRIPT>
                    $(".btn-group > ul li").on("click", function(){
                        $('#dropdown_language').html(this.innerHTML);
                        console.log(this.innerHTML);
                    });
                </SCRIPT>
                <!--
                <div>
                    <div>
                        <button id="rerun">Run last action</button>
                        <button id="select">Select an action</button>
                    </div>
                    <ul>
                        <li><a href="#">Open...</a></li>
                        <li><a href="#">Save</a></li>
                        <li><a href="#">Delete</a></li>
                    </ul>
                </div>
                -->
                <SCRIPT>$('#rerun').algoDropDown();</SCRIPT>
                
                <div id="CodeEditor" zstyle="height:95%;">
                    <div id="CodeEditorContainer" class="ui-layout-content" zstyle="height: 90%">
                        <textarea id="code" name="code" class="well" style="border: 1px solid #fff; height: auto;"><? include("inc_sample_r_code.php"); ?></textarea>
                    </div>                    
                </div>   
            </div>
            <div id="editor_status" class="footer">0,0 (Total: 0 Lines 0 Bytes)</div>
	</div>

	<div class="ui-layout-north"> 
            <div id="button_container" style="margin-left: 5px;">
                <div class="button-general" id="button_saveAlgorithm"><a href="javascript:void(0);" onclick="myIDE.save();"><img src="/images/glyphicons/glyphicons_232_cloud_white.png" class="button-general-icon"><?=$this->localization->buttons->SaveVisualizationtext; ?></a></div>
                <div class="button-spacer"></div>
                <div class="button-general"><a href="/ide/index" zonclick="startWizard();"><img src="/images/glyphicons/glyphicons_193_circle_ok_white.png" class="button-general-icon"><?=$this->localization->buttons->ValidateVisualizationtext; ?></a></div>
                <div class="button-spacer"></div>
                <div id="button_modifyAlgorithm" class="button-general disabled"><a href="javascript:void(0);" onclick="startWizard();"><img src="/images/glyphicons/MRR_Round_Play_white.png" class="button-general-icon"><?=$this->localization->buttons->TestVisualizationtext; ?></a></div> 
                <SPAN id="last_saved_container" style="float: right; white-space:nowrap;">Last saved <SPAN id="last_saved" class="loaded timeago" zstyle="float: right;">Never</SPAN></SPAN>
            </div>
        </div>
	<div class="ui-layout-south">
            <h3 class="header">Input Sample Data</h3>
            <DIV id="inputarea" class="ui-layout-content" zstyle="background-color: #fff; height: 120px;">
            </DIV>
        </div>
	<!-- <div class="ui-layout-west">  Inner - West</div> -->
	<div class="ui-layout-east">
            <h3 class="header">Output Preview</h3>
            <div class="ui-layout-content">    
                <iframe id="visualization_preview" zsrc="/visualization/index?algorithm_id=<?=$algoid;?>&datasource_id=2510" style="width: 98%; height: 96%;"></iframe>
            </div>
	</div>

</div>
<!-- END Layout Test -->

        <form action="https://localhost:8444/algorithms/save" method="POST">
            <INPUT type="hidden" name="algorithm_id" value="<?=$algoid; ?>">
            <INPUT type="hidden" name="authToken" value="<?=$this->token;?>">
        </form>
        <script>
        var sourceCodeOnChange = function(codeMirror) {
            var source = codeMirror.getValue();
            myIDE.set("sourceCode", source);
        }
        var HTMLCodeOnChange = function(codeMirror) {
            var source = codeMirror.getValue();
            myIDE.set("HTMLCode", source);
        } 
        var CSSCodeOnChange = function(codeMirror) {
            var source = codeMirror.getValue();
            myIDE.set("CSSCode", source);
        }        
        var cursorMove = function(codeMirror) {
            var source = codeMirror.getValue();
            var bytes = source.length;
            var lines = source.split("\n").length;
            var cursor = codeMirror.getCursor();
            codeMirror.setLineClass(hlLine, null, null);
            hlLine = codeMirror.setLineClass(codeMirror.getCursor().line, null, "activeline");            
            $('#editor_status').text((cursor.ch+1)+", "+(cursor.line+1)+" ("+lines+" lines "+bytes+" bytes)");
            //console.log(cursor);
                    //HTMLEditor.refresh();
                    //CSSEditor.refresh();
        }       
            
        var sourceEditor = CodeMirror.fromTextArea(document.getElementById("code"), {
            lineNumbers:true
        ,   onChange: sourceCodeOnChange
        ,   onCursorActivity: cursorMove
        });
        var hlLine = sourceEditor.setLineClass(0, "activeline"); 

        var refreshEditors = function() {
            setTimeout(function(){sourceEditor.refresh();}, 200);
            //console.log("DEBUG201210221645: refreshing editors");
            //sourceEditor.refresh();
            // Seems we need a slight delay before CodeMirror will actual render something - MRR20121022
            //setTimeout(function(){HTMLEditor.refresh();}, 200);
            //setTimeout(function(){CSSEditor.refresh();}, 200);
            //CSSEditor.refresh();
        }
        setTimeout(refreshEditors, 1000);
        //$(".CodeMirror").addClass("well-small");

        //$(".CodeMirror").css("height", "500px"); // Commented out - MRR 20121017
        //$(".CodeMirror-scroll").css("height", "500px"); // Commented out - MRR 20121017
        
        var inputparam_onclick = function (e, data) { 
                                            //alert(data.rslt.obj.data("id"));
                                            //console.log(data.rslt.obj.data);
                                            alert(data.rslt.obj.data("description"));
                                        };
    var editorResize;
    $(function () {
        editorResize = function(x,ui) {
            console.log("DEBUG201210221452: !!!!!!!!!!!!!!!!!!!!!! Resizing ",x);
            $('.CodeMirror-scroll').height($(".ui-layout-center").height()-140);            
        }
        //$("#CodeEditorContainer").resize(editorResize);
        //$('.ui-layout-center').resize(editorResize);
        console.log("DEBUG201210221706: CodeEditorContainer.height="+$("#CodeEditorContainer").height(),$("#CodeEditorContainer"));
        editorResize();
        //$(window).resize(editorResize);
        


	$("#outputparams").jstree({
                "themes" : {
                         "theme" : "apple",
                         "dots"  : true,
                         "icons" : false
                },

		"json_data" : {
	
                            "ajax" : {
				"url" : "/ide/outputparams",
				"data" : function (n) { 
					return { id : myIDE.id() ? myIDE.id() : 0 }; 
				}
                            }
			
		},
                "set_theme" : "apple",
		"plugins" : [ "themes", "json_data", "ui" ]
	}).bind("select_node.jstree", inputparam_onclick);
        
        var libMenu = function ($node) {
            return {
                "upload": {
                                    "label": "Upload a library",
                                    "action": function(obj){alert("ERROR201208190826: Sorry not implemented yet.");},
                },
            };
        };
        
	$("#libraries").jstree({
                "themes" : {
                         "theme" : "apple",
                         "dots"  : true,
                         "icons" : false
                },

		"json_data" : {
	
                            "ajax" : {
				"url" : "/viside/libraries",
				"data" : function (n) { 
					return { id : n.attr ? n.attr("id") : 0 }; 
				}
                            }
			
		},
                "progressive_render" : true,
                "set_theme" : "apple",
                "contextmenu": {
                    "items" : libMenu,
                },
		"plugins" : [ "themes", "json_data", "ui", "contextmenu" ]
	}).bind("select_node.jstree", inputparam_onclick);
        
        /*
        var dsretrieve = function(datasource_id){
            var stuff = myIDE.retrieveDataSource(2455);
            console.log("DEBUG201208210009: ");
            console.log(stuff);
            return stuff;
        };
        
        $.when(dsretrieve()).then(doInputParamsTable); // Note .when should call functions, .then should have function passed in
        */
    });

    var doInputParamsTable = function(datasource) {
        var processdata = function(jsonobj) {
            var headers = jsonobj["headers"];
            var data = jsonobj["data"];
            console.log("DEBUG201208210707: ");
            console.log(jsonobj);
            var table = $('<TABLE id="inputareatable" border="1"></TABLE>');
            var thead = $('<thead></thead>');
            var theadrow = $('<tr></tr>');
            
            for(var i=0; i<headers.length; i++) {
                theadrow.append($("<th width='100'>"+headers[i]+"</th>"));
            }

            thead.append(theadrow);
            table.append(thead);
            
            var rows;
            for(var row=0; row<data.length; row++) {
                //console.log(data[row]);
                var thisrow = $("<tr></tr>");
                for(var col=0; col<data[row].length; col++) {
                    thisrow.append("<TD width='100'>"+data[row][col]+"</TD>");
                }
                table.append(thisrow);
            }

            //console.log(""+table.html());
            $('#inputarea').html("");
            $('#inputarea').append(table);
            $("#inputarea").flexigrid();
            //$('#inputarea').html("<h1>hello</h1>");
        };
        
        $.when(datasource.getData({rowlimit: 200})).then(processdata);
    }
            
        </script>
<!-- Start Algorithm Properties -->
<DIV id="div_algorithm_properties" class="wizardBox" style="min-height: 550px;" zstyle="border: 5px solid red;">
    <h2><? echo $this->localization->Algorithm->IDE->Properties->Title; ?></h2>
    <BR><BR>
    <? echo $this->localization->Algorithm->IDE->Properties->Instructions; ?><BR><BR>
    
    <FORM>
    <div id="properties_tabs">
        <ul>
            <li><a href="#properties_general">General</a></li>
            <li><a href="#properties_details">Details</a></li>
        </ul>
        <div id="properties_general">
    <? echo $this->localization->Visualization->IDE->Properties->Instructions; ?><BR><BR>
        <LABEL for="form_algorithm_name"><? echo $this->localization->Algorithm->IDE->Properties->Form->Labels->Title; ?></LABEL>
        <INPUT name="form_algorithm_name" id="form_algorithm_name" TYPE="text" SIZE="40" style="width: 500px;" onkeyup="validateAlgorithmProperties();">
        
        <LABEL for="form_algorithm_description"><? echo $this->localization->Algorithm->IDE->Properties->Form->Labels->Description; ?></LABEL>
        <TEXTAREA name="form_algorithm_description" id="form_algorithm_description" TYPE="text" SIZE="40" style="width: 500px; height: 100px;" onkeyup="validateAlgorithmProperties();"></TEXTAREA>
        
        <LABEL for="form_algorithm_tags"><? echo $this->localization->Algorithm->IDE->Properties->Form->Labels->Tags; ?></LABEL>
        <INPUT name="form_algorithm_tags" id="form_algorithm_tags" TYPE="text" SIZE="40" style="width: 500px;" onkeyup="validateAlgorithmProperties();">

        <BR clear="all">
        <LABEL for="form_inputParams_from_DataSource"><INPUT TYPE="checkbox" name="form_inputParams_from_DataSource" id="form_inputParams_from_DataSource" value="1" CHECKED  style="display: inline;"><?=$this->localization->IDE->Properties->Form->Labels->inputParamsFromDataSource; ?></LABEL>
        <div id="button_datasource_select" class="button-general"><a href="javascript:void(0);" onclick="showWizardPopup($('#div_datasources_list'));"><?=$this->localization->Algorithm->IDE->Properties->Form->Buttons->DataSourcePopup; ?></a></div>    
        <BR clear="all">        
        </div>
        
        <div id="properties_details">
                    <TEXTAREA id="form_visualization_details" class="htmlEditor" style="width:100%"></TEXTAREA>
        <SCRIPT>
$(function(){
//tinyMCE.init({
$('.htmlEditor').tinymce({
        // General options
        script_url: '/js/tiny_mce/tiny_mce.js',
        mode : "specific_textareas",
        editor_selector: "htmlEditor",
        theme : "advanced",
        plugins : "imagemanager,autolink,lists,spellchecker,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template",

        // Theme options
        //theme_advanced_buttons1 : "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,formatselect,fontselect,fontsizeselect",
        theme_advanced_buttons1 : "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,formatselect,fontselect,fontsizeselect",
        theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
        theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
        theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,spellchecker,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,blockquote,pagebreak,|,insertfile,insertimage",
        theme_advanced_toolbar_location : "top",
        theme_advanced_toolbar_align : "left",
        theme_advanced_statusbar_location : "bottom",
        theme_advanced_resizing : true,

        // Skin options
        skin : "o2k7",
        skin_variant : "silver",

        // Example content CSS (should be your site CSS)
        content_css : "/css/style.css",

        // Drop lists for link/image/media/template dialogs
        template_external_list_url : "js/template_list.js",
        external_link_list_url : "js/link_list.js",
        external_image_list_url : "js/image_list.js",
        media_external_list_url : "js/media_list.js",

        // Replace values for the template plugin
        template_replace_values : {
                username : "Some User",
                staffid : "991234"
        }
});
});
        </SCRIPT>               
        </div>
    </div>
    </FORM>
    <div id="button_properties_close" class="button-cancel disabled" style="float: right;"><a href="javascript:void(0);" onclick="closeAlgorithmProperties();"><?=$this->localization->buttons->closetext; ?></a></div>
</DIV>
<!-- End Algorithm Properties -->

<!-- Begin DataSources List -->
<DIV id="div_datasources_list" class="wizardBox" style="min-height: 550px;" zstyle="border: 5px solid red;">
    <h2><? echo $this->localization->IDE->DataSources->DataSourceListTitle; ?></h2>
    <BR>
    <? echo $this->localization->IDE->DataSources->Instructions; ?><BR><BR>
    <? include_once("datasources_list.php"); ?>
    <div id="button_datasource_close" class="button-cancel disabled" style="float: right;"><a href="javascript:void(0);" onclick="closeDataSourceList();"><?=$this->localization->buttons->closetext; ?></a></div>
</div>
<!-- End DataSources List -->

<!-- Begin inputParams List -->
<DIV id="div_inputparams_list" class="wizardBox" style="min-height: 550px;" zstyle="border: 5px solid red;">
    <h2><? echo $this->localization->IDE->InputParams->Title; ?></h2>
    <BR>
    <? echo $this->localization->IDE->InputParams->Instructions; ?><BR><BR>    
    <FORM>
        <TEXTAREA NAME="form_inputparams" id="form_inputparams" style="width: 800px;" cols="500" rows="30"></TEXTAREA>
    </FORM>
    <div id="button_inputparams_close" class="button-cancel" style="float: right;"><a href="javascript:void(0);" onclick="closeInputParams();"><?=$this->localization->buttons->closetext; ?></a></div>
</div>
<!-- End inputParams List -->

<!-- Begin outputParams List -->
<DIV id="div_outputparams_list" class="wizardBox" style="min-height: 550px;" zstyle="border: 5px solid red;">
    <h2><? echo $this->localization->IDE->OutputParams->Title; ?></h2>
    <BR>
    <? echo $this->localization->IDE->OutputParams->Instructions; ?><BR><BR>        
    <FORM>
        <LABEL for="form_outputparams">Output Parameters</LABEL>
        <TEXTAREA NAME="form_outputparams" id="form_outputparams" style="width: 800px;" cols="500" rows="30"></TEXTAREA>
    </FORM>
    <div id="button_outputparams_close" class="button-cancel" style="float: right;"><a href="javascript:void(0);" onclick="closeOutputParams();"><?=$this->localization->buttons->closetext; ?></a></div>
</div>
<!-- End outputParams List -->
<!-- END modify_algorithms_editor -->

<BR><BR>
<? 
//echo pagefooter(); 
?>
