<?php 

$params = array(
    "Word"              => array(
                                "description"   => "The word in the dictionary.",
                                "datatype"      => "text",
                                "minlength"     => "1B",
                                "maxlength"     => "45B",
                            ),
    "Distance to Word1" => array(
                                "description"   => "The distance from Word to Word1 (i.e. Hello)",
                                "datatype"      => "real",
                                "minvalue"     => "0.000000000001",
                                "maxvalue"     => "10000000000000",                                  
                                ),
    "Distance to Word1" => array(
                                "description"   => "The distance from Word to Word1 (i.e. Hello)",
                                "datatype"      => "real",
                                "minvalue"     => "0.000000000001",
                                "maxvalue"     => "10000000000000",                                  
                                ),    
);

function paramToJsonArray($params) {
    $return = array();
    foreach ($params as $key=>$value) {
        //echo $key."<BR>";
        if(isset($params[$key]["children"])) {
            // Call recursive to get children
            $children = paramToJsonArray($params[$key]["children"]);
            $attr = $params[$key];
            unset($attr["children"]);
            $return[]=array(
                "data"      =>$key." [".$params[$key]["datatype"]."]",
                "children"  =>$children, 
                "metadata"  =>$params[$key],
            );
        } else {
            $return[]=array(
                "data"      =>$key." [".$params[$key]["datatype"]."]",
                "metadata"  =>$params[$key],
            );
        }
    }
    return $return;
}

echo json_encode(paramToJsonArray($params)); 
?>