<?php ?>
<? //require_once realpath(dirname(__FILE__).'/inc/config.php'); ?>
<? require_once ('AlgorithmsIO/config.php'); ?>
<? 
//$wizard_height="500px";
global $GLOBALS;
//$GLOBALS["htmllinktags"] = <<<EOS
$htmllinktags = <<<EOS
<link rel="stylesheet" href="/css/dashboard.css">
<!-- Bootstrap CSS Toolkit styles -->
<link rel="stylesheet" href="/css/fileupload/bootstrap.min.css">
<!-- Bootstrap styles for responsive website layout, supporting different screen sizes -->
<link rel="stylesheet" href="/css/fileupload/bootstrap-responsive.min.css">
<!-- Bootstrap CSS fixes for IE6 -->
<!--[if lt IE 7]><link rel="stylesheet" href="/css/fileupload/bootstrap-ie6.min.css"><![endif]-->
<!-- CSS to style the file input field as button and adjust the Bootstrap progress bars -->
<link rel="stylesheet" href="/css/fileupload/jquery.fileupload-ui.css">
<!-- Shim to make HTML5 elements usable in older Internet Explorer versions -->
<!--[if lt IE 9]><script src="/js/html5.js"></script><![endif]-->

<link rel="stylesheet" type="text/css" href="/css/flexigrid/flexigrid.pack.css" />
<link rel="stylesheet" href="/js/codemirror/codemirror.css">
EOS;
#<!--[if lt IE 9]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->

$javascript = <<<EOS
<script src="/js/bootstrap-tab.js"></script>
<script src="/js/jquery.jstree/jquery.jstree.js"></script>
EOS;

echo pageheader(array(
	"htmllinktags"	=>$htmllinktags,
	"javascript"	=>$javascript,
        "body_css"      =>"max", // Break out of the template width bindings
)); 
?>
<SCRIPT src="/js/algo.js"></script>
<div id="button_container" style="margin-left: 5px;">
    <div class="button-general"><a href="/market/algorithms"><img src="/images/glyphicons/glyphicons_232_cloud_white.png" class="button-general-icon"><?=$this->localization->buttons->SaveAlgorithmtext; ?></a></div>
    <div class="button-spacer"></div>
    <div class="button-general"><a href="/ide/index" zonclick="startWizard();"><img src="/images/glyphicons/glyphicons_193_circle_ok_white.png" class="button-general-icon"><?=$this->localization->buttons->ValidateAlgorithmtext; ?></a></div>
    <div class="button-spacer"></div>
    <div id="button_modifyAlgorithm" class="button-general disabled"><a href="javascript:void(0);" onclick="startWizard();"><img src="/images/glyphicons/MRR_Round_Play_white.png" class="button-general-icon"><?=$this->localization->buttons->TestAlgorithmtext; ?></a></div> 
</div>
<BR clear=all> <BR clear=all>

<script src="/js/codemirror/codemirror.js"></script>
<script src="/js/codemirror/mode/r/r.js"></script>

<div id="main_container" style="width: 100%; margin-left: 5px;">
    <div id="code_container" style="width: 70%; height: 100%; float: left; zborder: 1px solid #f00;">
        <form><textarea id="code" name="code" class="well" style="border: 1px solid #fff; height: 500px;">
        <? include("inc_sample_r_code.php"); ?>
        </textarea></form>
        <script>
            var editor = CodeMirror.fromTextArea(document.getElementById("code"), {lineNumbers:true,});
            console.dir($('#'));
            $(".CodeMirror").addClass("well-small");
            $(".CodeMirror").css("background-color", "#eee");
            $(".CodeMirror").css("height", "500px");
            $(".CodeMirror-scroll").css("height", "500px");
            //$(".CodeMirror").css("width", "1500px");
            //$(".CodeMirror-scroll").css("width", "1500px");
        
        var inputparam_onclick = function (e, data) { 
                                            //alert(data.rslt.obj.data("id"));
                                            //console.log(data.rslt.obj.data);
                                            alert(data.rslt.obj.data("description"));
                                        };
           
        $(function () {
	$("#inputparams").jstree({
                "themes" : {
                         "theme" : "apple",
                         "dots"  : true,
                         "icons" : false
                },

		"json_data" : {
	
                            "ajax" : {
				"url" : "/ide/inputparams",
				"data" : function (n) { 
					return { id : n.attr ? n.attr("id") : 0 }; 
				}
                            }
			
		},
                "set_theme" : "apple",
		"plugins" : [ "themes", "json_data", "ui" ]
	}).bind("select_node.jstree", inputparam_onclick);

	$("#outputparams").jstree({
                "themes" : {
                         "theme" : "apple",
                         "dots"  : true,
                         "icons" : false
                },

		"json_data" : {
	
                            "ajax" : {
				"url" : "/ide/outputparams",
				"data" : function (n) { 
					return { id : n.attr ? n.attr("id") : 0 }; 
				}
                            }
			
		},
                "set_theme" : "apple",
		"plugins" : [ "themes", "json_data", "ui" ]
	}).bind("select_node.jstree", inputparam_onclick);
        
	$("#libraries").jstree({
                "themes" : {
                         "theme" : "apple",
                         "dots"  : true,
                         "icons" : false
                },

		"json_data" : {
	
                            "ajax" : {
				"url" : "/ide/libraries",
				"data" : function (n) { 
					return { id : n.attr ? n.attr("id") : 0 }; 
				}
                            }
			
		},
                "progressive_render" : true,

                "set_theme" : "apple",
		"plugins" : [ "themes", "json_data", "ui" ]
	}).bind("select_node.jstree", inputparam_onclick);
        
});

            
        </script>
        <div id="input_params" class="well" style="width: 46%; float: left; margin-top: 5px;">
            Input
            <DIV id="inputarea" class="well" style="background-color: #fff; height: 120px;"></DIV>
        </div>
        <div id="output_params" class="well" style="width: 46%; float: right; margin-top: 5px; margin-left: 5px;">
            Output
            <DIV id="outputarea" class="well" style="background-color: #fff; height: 120px;"></DIV>
        </div>
    </div>
    <div id="right_container" style="width:18%; float:left; margin-left: 10px;">
        <div id="library_container" class="well" zstyle="width: 18%; height: 500px; float: left; margin-left: 10px;">
            <div id="library_title" class="title"><?=$this->localization->IDE->Libraries->LibraryTitletext; ?></div>
            <div id="libraries" style="height: 200px; overflow-y: scroll;"></div>
        </div>
        <div id="inputparams_container" class="well" zstyle="width: 18%; height: 500px; float: left; margin-left: 10px;">
            <div id="inputparams_title" class="title"><?=$this->localization->IDE->Libraries->InputParamsTitletext; ?></div>
            <div id="inputparams"></div>
        </div>
        <div id="outputparams_container" class="well" zstyle="width: 18%; height: 500px; float: left; margin-left: 10px;">
            <div id="outputparams_title" class="title"><?=$this->localization->IDE->Libraries->OutputParamsTitletext; ?></div>
            <div id="outputparams"></div>
        </div>
    </div>
</div>
<? # print_r($localstrings); ?>
<BR><BR><BR>

<!-- END modify_algorithms_editor -->

<BR><BR>
<? echo pagefooter(); ?>
