<?php ?>
<? //require_once realpath(dirname(__FILE__).'/inc/config.php'); ?>
<? require_once ('AlgorithmsIO/config.php'); ?>
<? 
//$wizard_height="500px";
global $GLOBALS;
//$GLOBALS["htmllinktags"] = <<<EOS
$htmllinktags = <<<EOS
<link rel="stylesheet" href="/css/dashboard.css">
<!-- Bootstrap CSS Toolkit styles -->
<link rel="stylesheet" href="/css/fileupload/bootstrap.min.css">
<!-- Bootstrap styles for responsive website layout, supporting different screen sizes -->
<link rel="stylesheet" href="/css/fileupload/bootstrap-responsive.min.css">
<!-- Bootstrap CSS fixes for IE6 -->
<!--[if lt IE 7]><link rel="stylesheet" href="/css/fileupload/bootstrap-ie6.min.css"><![endif]-->
<!-- CSS to style the file input field as button and adjust the Bootstrap progress bars -->
<link rel="stylesheet" href="/css/fileupload/jquery.fileupload-ui.css">
<!-- Shim to make HTML5 elements usable in older Internet Explorer versions -->
<!--[if lt IE 9]><script src="/js/html5.js"></script><![endif]-->

<link rel="stylesheet" type="text/css" href="/css/flexigrid/flexigrid.pack.css" />
EOS;
#<!--[if lt IE 9]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->

$API_JS = $this->API_URL."Jssdk/?authToken=".$this->token;
$VIS_JS = $this->API_URL."JsLibrary/";
$API_Access_Counts = $this->API_URL."Credits/APIAccesses?authToken=".$this->token;
$javascript = <<<EOS
<script src="/js/bootstrap-tab.js"></script>
<script type="text/javascript" src="$API_JS"></script>    
<script src="/js/Dashboard.js"></script>
<script src="/js/jquery.timeago.js"></script>
<script type="text/javascript" src="/js/flexigrid/flexigrid.js"></script>
<script type="text/javascript" src="/js/algo_job.js"></script>
EOS;

$javascript .= '<script language="javascript" type="text/javascript" src="'.$VIS_JS.'visualizations/flot/jquery.flot.js?authToken='.$this->token.'"></script>';
$javascript .= '<script language="javascript" type="text/javascript" src="'.$VIS_JS.'visualizations/flot/jquery.flot.selection.js?authToken='.$this->token.'"></script>';

echo pageheader(array(
	"htmllinktags"	=>$htmllinktags,
	"javascript"	=>$javascript,
        "nav_tab"       =>"jobs",    
        "view"          =>$this    
)); 
?>
<SCRIPT src="/js/algo.js"></script>
<SCRIPT>
var flow_id = null;
<? if(isset($this->params["flow_id"]) && $this->params["flow_id"] > 0) { ?>
flow_id = <?=$this->params["flow_id"]; ?>;
<? } ?>
$(function (){
    //startWizard();
});
</SCRIPT>
<div id="holder" style="min-height: 600px">

</div> <!-- END holder -->
<? include_once("wizard_AddJob.php"); ?>
<BR><BR>
<? echo pagefooter(); ?>
