<div class="layout">
  <!-- body starts -->
  <div class="body-outer">
    <div class="body">
  <!-- aboutus box -->	      
   <div class="about-box">
   <h3>Algorithms</h3>

  <div class="api-box-2">


<!-- boostrap scaffolding -->
    <div class="container-fluid">
<div class="row-fluid">
<div class="span2">
<!--Sidebar content-->
<ul>
  <li>Basic Usage</li>
    <ul>
      <li><a href="/docs/restapi">REST API</a></li>
      <li><a href="/docs/dataset">Dataset</a></li>
      <li><a href="/docs/algorithms">Algorithms</a></li>
      <li><a href="/docs/credits">Credits</a></li>
    </ul>
  <li>Recommendation</li>
    <ul>
      <li><a href="/docs/collaborativefiltering">Collaborative Filtering</a></li>
    </ul>
  <li><a href="/docs/clustering">Clustering</a></li>
  <li><a href="/docs/classification">Classification</a></li>
  <li><a href="/docs/mapreduce">Map Reduce Jobs</a></li>
  <li><a href="/docs/pig">Pig Jobs</a></li>
  <li><a href="/docs/workflow">Workflow</a></li>
</ul>

<pre>
</div>
<div class="span10">
<!-- Main Content Area -->

<p>This REST endpoint will allow you to list all the algorithms in the system.<br>
    <b><i>Please note that you cannot use cut&paste with this command. </b></i></p>

<pre>
curl -H "authToken: &LT;authToken&GT;"
https://v1.api.algorithms.io/algorithms  </pre>
<p.>
The returned result is: <br>
<pre>
{"all":
[
{
  "id": 7,
  "type": "synchronous",
  "class": "/DataManipulation",
  "name": "Search and Replace",
  "implementation_class": "DataSourceManipulations_searchAndReplaceColumnCSV",
  "implementation_type": "1",
  "credits_cost": "1",
  "description": "",
  "created": "2012-04-26 22:59:15",
  "last_modified": "2012-04-26 22:59:15"
},
{
  "id": 19,
  "type": "synchronous",
  "class": "/Machine Learning/Recommenders",
  "name": "Get Recommendation ItemBaseRecommender - Sime Item City Block",
  "implementation_class": "GetRecommendation_SimItemCityBlock",
  "implementation_type": "3",
  "credits_cost": "1",
  "description": "Returns a set of recommendations",
  "created": "2012-08-02 00:48:02",
  "last_modified": "2012-08-02 00:48:02"
}
....
....
}]
}</pre>
</p>
    

<!-- bootstrap scaffolding -->
 </div>
</div>
</div>



  </div>
    <div class="cl"></div>
   </div>   
  <!-- aboutus box box -->	      
    <div class="cl"></div>
   </div>
  </div>
