<div class="layout">
  <!-- body starts -->
  <div class="body-outer">
    <div class="body">
  <!-- aboutus box -->	      
   <div class="about-box">
   <h3> Collaborative Filtering</h3>

  <div class="api-box-2">


<!-- boostrap scaffolding -->
    <div class="container-fluid">
<div class="row-fluid">
<div class="span2">
<!--Sidebar content-->
<ul>
  <li>Basic Usage</li>
    <ul>
      <li><a href="/docs/restapi">REST API</a></li>
      <li><a href="/docs/dataset">Dataset</a></li>
      <li><a href="/docs/algorithms">Algorithms</a></li>
      <li><a href="/docs/credits">Credits</a></li>
    </ul>
  <li>Recommendation</li>
    <ul>
      <li><a href="/docs/collaborativefiltering">Collaborative Filtering</a></li>
    </ul>
  <li><a href="/docs/clustering">Clustering</a></li>
  <li><a href="/docs/classification">Classification</a></li>
  <li><a href="/docs/mapreduce">Map Reduce Jobs</a></li>
  <li><a href="/docs/pig">Pig Jobs</a></li>
  <li><a href="/docs/workflow">Workflow</a></li>
</ul>

</div>
<div class="span10">
<!-- Main Content Area -->


<p>The most basic example of Collaborative Filtering can be seen when you are shopping.  When you are looking at a particular item, you may also see Recommended Products, often under the title “Customers who has viewed this item also viewed these items”.  Collaborative Filtering with the right dataset will provide you with this type of recommendations.</p>

    <p>By using the Movie Lens dataset, you can find additional movie recommendations.  For example, if you enjoy the movie “The Terminator”, and you want to get a list of other similar movies, you would do this:</p>

<p>
  1. Upload the data set. This will return to you a datasource_id_seq number.  This is the ID of the file you have just uploaded.  This ID will be used on the subsequent API calls.<br/>
  <pre>curl -i  -H "authToken: &LT;authToken&GT;"
        -H "type:rec"
        -H "name:Movie_Lens_100k" 
        -H "description:100k rows of user prefs" 
        -H "version:1" 
        -F theFile=@Movie_Lens_100k_data.csv
        https://v1.api.algorithms.io/dataset
    </pre>
</p>



<p>
  2. Inform the Algorithms.io system on which field is the user, item, and preference field.  This might take some a while depending on your dataset size.
        &nbsp;&nbsp;&nbsp;&nbsp;
  <pre>
curl -i 
    -d 'job_params={
        "job":{
            "algorithm":{
                "id":"13"
                },
            "input_variables":{
                "datasource_id_seq":"ID Returned in Step #1",
                "field_user_id":"user",
                "field_item_id": "item",
                "field_preference":"pref"
                }
            }
        }' 
        -H "authToken: &LT;authToken&GT;" 
        https://v1.api.algorithms.io/jobs
  </pre>
The returned result is: <pre>
    {"output":
        {"api":{
            "Authentication":"Success"
            },
        "data":{
            "field_map_id":"694",
            "mapping":{
                "outcome":"Success",
                "TotalRows":14696
                }
            }
        }
    }
]
  </pre>
</p>



<p>
  3. Get a recommendations for the movie “Terminator The 1984”
  <pre>
curl -i 
    -d 'job_params={
        "job":{
            "algorithm":{
                "id":"14"
                },
            "input_variables":{
                "datasource_id_seq":"ID Returned in Step #1",
                "type":"item",
                "item":"Terminator The 1984"
                }
            }
        }' 
        -H "authToken: &LT;authToken&GT;" 
         https://v1.api.algorithms.io/jobs -v
  </pre>
The returned result is:
<pre>
[
    {"output":{
        "api":{
            "Authentication":"Success"
            },
        "data":{
            "recommendation":[
        {"id":"Sudden Death 1995","value":"0.95996654"},
        {"id":"Sword in the Stone The 1963","value":"0.9511138"},
        {"id":"Empire Strikes Back The 1980","value":"0.95010316"},
        {"id":"Die Hard 2 1990","value":"0.945785"},
        {"id":"Clear and Present Danger 1994","value":"0.9444163"},
        {"id":"Return of the Jedi 1983","value":"0.9439957"},
        {"id":"Blade Runner 1982","value":"0.9425006"},
        {"id":"Island of Dr. Moreau The 1996","value":"0.9395942"},
        {"id":"Fugitive The 1993","value":"0.9383732"},
        {"id":"Waterworld 1995","value":"0.93799603"},
        {"id":"Interview with the Vampire 1994","value":"0.93409985"},
        {"id":"Raiders of the Lost Ark 1981","value":"0.93382645"},
        {"id":"Timecop 1994","value":"0.9330071"}]
    }}}] 
</pre>
</p>
    

<!-- bootstrap scaffolding -->
 </div>
</div>
</div>



  </div>
    <div class="cl"></div>
   </div>   
  <!-- aboutus box box -->	      
    <div class="cl"></div>
   </div>
  </div>
</div>
