<div class="layout">
  <!-- header ends -->
  <!-- body starts -->
  <div class="body-outer">
    <div class="body">
  <!-- aboutus box -->	      
   <div class="about-box">
   <h3>Credits</h3>

  <div class="api-box-2">


<!-- boostrap scaffolding -->
    <div class="container-fluid">
<div class="row-fluid">
<div class="span2">
<!--Sidebar content-->
<ul>
  <li>Basic Usage</li>
    <ul>
      <li><a href="/docs/restapi">REST API</a></li>
      <li><a href="/docs/dataset">Dataset</a></li>
      <li><a href="/docs/algorithms">Algorithms</a></li>
      <li><a href="/docs/credits">Credits</a></li>
    </ul>
  <li>Recommendation</li>
    <ul>
      <li><a href="/docs/collaborativefiltering">Collaborative Filtering</a></li>
    </ul>
  <li><a href="/docs/clustering">Clustering</a></li>
  <li><a href="/docs/classification">Classification</a></li>
  <li><a href="/docs/mapreduce">Map Reduce Jobs</a></li>
  <li><a href="/docs/pig">Pig Jobs</a></li>
  <li><a href="/docs/workflow">Workflow</a></li>
</ul>

</div>
<div class="span10">
<!-- Main Content Area -->

<p>This REST endpoints helps you perform action on the credits that you currently have.    <br>
    <b><i>Please note that you cannot use cut&paste with this command. </b></i></p>

  Show current credits available:
  <pre>
curl -H "authToken: &LT;authToken&GT;"
https://v1.api.algorithms.io/credits -v</pre>
<p.>
    <br>The returned result is something like: <br>
<pre>
{"credits_available":"10000"} 
</pre>
<!-- bootstrap scaffolding -->
 </div>
</div>
</div>



  </div>
    <div class="cl"></div>
   </div>   
  <!-- aboutus box box -->	      
    <div class="cl"></div>
   </div>
  </div>
  <!-- body ends -->
</div>
