  <!-- body starts -->
  <div class="body-outer">
    <div class="body">
  <!-- aboutus box -->	      
   <div class="about-box">
   <h3> API Usage</h3>

  <div class="api-box-2">


<!-- boostrap scaffolding -->
    <div class="container-fluid">
<div class="row-fluid">
<div class="span2">
<!--Sidebar content-->
<ul>
  <li>Basic Usage</li>
    <ul>
      <li><a href="/docs/restapi">REST API</a></li>
      <li><a href="/docs/dataset">Dataset</a></li>
      <li><a href="/docs/algorithms">Algorithms</a></li>
      <li><a href="/docs/credits">Credits</a></li>
    </ul>
  <li>Recommendation</li>
    <ul>
      <li><a href="/docs/collaborativefiltering">Collaborative Filtering</a></li>
    </ul>
  <li><a href="/docs/clustering">Clustering</a></li>
  <li><a href="/docs/classification">Classification</a></li>
  <li><a href="/docs/mapreduce">Map Reduce Jobs</a></li>
  <li><a href="/docs/pig">Pig Jobs</a></li>
  <li><a href="/docs/workflow">Workflow</a></li>
</ul>

</div>
<div class="span10">
<!-- Main Content Area -->

   <h2>Coming Soon</h2> 

<!-- bootstrap scaffolding -->
 </div>
</div>
</div>



  </div>
    <div class="cl"></div>
   </div>   
  <!-- aboutus box box -->	      
    <div class="cl"></div>
   </div>
  </div>
