<div class="layout">
  <div class="body-outer">
    <div class="body">
   <div class="about-box">
   <h3>About Us</h3>
<div class="span8" style="font-size: 14px; font-family: " helvetica="" neue",helvetica,arial,sans-serif;"="">
Algorithms.io was founded in 2012 by a group of engineers developing mobile applications based on machine learning algorithms.  The team realized that finding the right algorithms and developing the back-end to run them is not easy.  The team set out to solve this problem so other developers could focus on building great applications, not data infrastructure.  

<br>
<br>
The Algorithms.io platform enables quick and easy implementation of algorithms to get the most from your data.  Build a new application on top of our RESTful API or process your data with our library of standard and machine learning algorithms.  Host your specialized algorithms on our cloud data infrastructure and access them on demand.  
<br>
<br> Algorithms.io - your data science team in the cloud. 
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
</div>
    <div class="span4"> 
        <address>
            <strong>Algorithms.io Inc.</strong><br>
            800 West El Camino Real Suite 180 <br> Mountain View CA, 94040 <br>United States of America
            <br>
            <br>
            <a href="/contact/" class="btn btn-large btn-primary">Contact Us</a>    
    
        </address>
    </div>
    </p>
<br>
   </div>   
  <!-- aboutus box box -->	      
    <div class="cl"></div>
   </div>
  </div>
</div>
