  <div class="banner-outer">
    <div class="banner-inner">
      <div class="banner">

     <script src="/js/raphael-min.js" type="text/javascript" charset="utf-8"></script> 


<div id="myCarousel" class="carousel slide" style="width:1045px; height: 320px;" data-pause="hover">
<div class="carousel-inner">

        <div class="active item">
                <div style="background-repeat: no-repeat; background-image:url('/images/main.png'); width:1045px; height: 320px;">  
                    <div style="white-space: nowrap; position: relative; top: 220px;left: 190px;">
                                        <a class="btn btn-large btn-primary" style="font-size: 18px; width: 150px; font-style: normal;" type="button" href="/index/technology">Learn More &raquo;</a>
                                        <a class="btn btn-large btn-warning" style="font-style: normal; font-size: 18px; width: 150px;" type="button" href="/contact/register">Request Access &raquo;</a>
                    </div>

                </div>
        </div>

        <div class="item">
                <div onclick="document.location='/index/technology/'" style="cursor:pointer;background-repeat: no-repeat; background-image:url('/images/banner_data.png'); width:1045px; height: 320px;">

                </div>
        </div>
        
        <div class="item">
        <div style="background-repeat: no-repeat; background-image:url('/images/banner_simple.png'); width:1045px; height: 320px;">
                    <div style="white-space: nowrap; position: relative; top: 160px;left: 450px;">
                                        <a class="btn btn-large btn-primary" style="font-size: 18px; background: #3c92c7; width: 130px; font-style: normal;" type="button" href="/index/technology">Learn More &raquo;</a>
                    </div>

                </div>
        </div>

 </div>

        <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
        <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
        </div>

      </div>
    </div>
  </div>
  <!-- header ends -->
  <!-- body starts -->
  <div class="body-outer">
    <div class="body" style="width: 1045px;padding-left: 20px;">

 <!-- Example row of columns -->
      <div class="row-fluid">
        <div class="span4">
          <h2 style="font-style: normal">App Developers</h2>
          <p>Build smarter apps faster on top of our data infrastructure.
            <br> <a href="/index/solutions#developers">Learn More</a>
            <br></p>
        </div>
        <div class="span4">
          <h2 style="font-style: normal">Tech Companies</h2>
          <p>Big data solutions for growing technology companies.
            <br> <a href="/index/solutions#companies">Learn More</a>
            <br></p>
       </div>
        <div class="span4">
          <h2 style="font-style: normal">Data Scientists</h2>
          <p>Host and distribute algorithms written in multiple programming languages.
            <br> <a href="/index/solutions#scientists">Learn More</a>
            <br></p>
        </div>
      </div>
      </div>
    </div>  
