  <div class="banner-outer">
    <div class="banner-inner">
      <div class="banner">
        	<div class="simple-input"> 
                    <div style="height: 10px;"><br></div> 
                    Your apps have data.
                    <div style="height: 10px;"><br></div> 
                    Your customers want intelligent feedback.
                    <div style="height: 10px;"><br></div> 
                    But, you are not a data scientist.
                    <div style="height: 10px;"><br></div> 
                    Our platform provides the solution. 
                    <div style="height: 10px;"><br></div> 
                </div>
                <br>
                        <button class="btn btn-large btn-block btn-primary" style="font-size: 24px; width: 720px;" type="button" onclick="document.location=/signup/">Sign Up to find out more &raquo;</button>


      </div>
    </div>
  </div>
  <!-- header ends -->
  <!-- body starts -->
  <div class="body-outer">
    <div class="body">

 <!-- Example row of columns -->
      <div class="row">
        <div class="span4">
          <h2>Easy to use</h2>
          <p>Access and chain complex algorithms in a few lines of code.
            <br><a href="/index/api/">see more</a></p>
        </div>
        <div class="span4">
          <h2>Restful API</h2>
          <p>Embed intelligent algorithms into any application.
            <br><a href="/index/api/">see more</a></p>
       </div>
        <div class="span4">
          <h2>Zero Maintenance</h2>
          <p>Just code and don't worry about scaling or library changes.
            <br><a href="/index/api/">see more</a></p>
        </div>
      </div>
      </div>
    </div>  
</div>
