<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>ImarketingB2B</title>
<link rel="stylesheet" href="css/style.css" type="text/css">
<link rel="shortcut icon" href="/images/icon.ico" type="image/x-icon">
<link rel="icon" href="/images/icon.ico" type="image/x-icon">
<script src="js/jquery.js" type="text/javascript"></script>

</head>
<body>
<div class="signinBox" style="display:block; margin:0; left:0; top:0; position:relative"> <span class="topbg"></span>
  <div class="midbg">
    <div class="container">
      <h2>Sign In to algorithms</h2>
      <div class="row">
        <input name="" class="inputtxt" type="text" placeholder="Your Email Address" />
      </div>
      <div class="row">
        <input name="" class="inputtxt" type="text" placeholder="Your Password" />
      </div>
      <div class="row2">
        <input name="" type="image" src="images/submit-btn-bg.png" value="submit" />
        </div>
    </div>
  </div>
  <span class="bottbg"></span> </div>
</body>
</html>
