<div class="container">
	
	<h1>Download and login information:</h1>

	<P>
		1) Download the latest ova <a href="https://s3.amazonaws.com/ova.userRobot.com/userrobot_v1.1.ova">here</a>
	</P>
	<p>
		2) Login information:<br/>
		User: admin@userrobot.com<br/>
		Password: UserMonitoringIsCool
	</p>
	<p>
		3) It is currently set to use DHCP but you can change it to a static IP via this file: /etc/network/interfaces
	</p>

      
</div>