  <!-- header ends -->
  <!-- body starts -->
  <div class="body-outer">
    <div class="body">
   <div class="about-box">
   <h3>Pricing</h3>
     <div class="content-div npl">
     </div>
     <div class="algo-pricing-container">
        <div class="heading-bg">
          <div class="colum"> <span>Basic</span> </div>
          <div class="colum"> <span>Entry </span></div>
          <div class="colum"><span> Premium</span> </div>
          <div class="colum"> <span>Enterprise </span></div>
          <div class="cl"></div>
        </div>
        <div class="repeat-bg">
          <div class="sep-row padding1">
            <div class="colum">
              <h3 class="free">Free </h3>
            </div>
            <div class="colum">
              <h3><br> Free Trial </h3>
            </div>
            <div class="colum">
              <h3> 
                <br>
                Free Trial</h3>
            </div>
            <div class="colum">
              <h3 class="free">Contact Us </h3>
            </div>
            <div class="cl"></div>
          </div>
          <div class="sep-row">
            <div class="colum"> 500 Credits/Monthly </div>
            <div class="colum"> 10,000 Credits/Monthly </div>
            <div class="colum"> 100,000 Credits/Monthly </div>
            <div class="colum"> Unlimited </div>
            <div class="cl"></div>
          </div>
          <div class="sep-row">
            <div class="colum"> 5gb Data/Storage Monthly</div>
            <div class="colum"> 200gb Data/Storage Monthly</div>
            <div class="colum">1TB Data/Storage Monthly</div>
            <div class="colum"> Unlimited</div>
            <div class="cl"></div>
          </div>
          <div class="sep-row">
            <div class="colum"> Email Support</div>
            <div class="colum"> 8hr Support</div>
            <div class="colum"> 16hr Support</div>
            <div class="colum"> Unlimited Support</div>
            <div class="cl"></div>
          </div>
          <div class="sep-row last">
            <div class="colum"> 

                    <a href="/billing/offering1"></a>
                    <h3>Free</h3>
            </div>
            <div class="colum">

                    <a href="/contact/" class="btn btn-large btn-primary">Contact Us</a>
            </div>
            <div class="colum"> 
                    <a href="/contact/" class="btn btn-large btn-primary">Contact Us</a>
            </div>
            <div class="colum"> 
                    <a href="/contact/" class="btn btn-large btn-primary">Contact Us</a>
            </div>
            <div class="cl"></div>
          </div>
        </div>
        <div class="bottom-curve">&nbsp;</div>
      </div>
    <div class="cl"></div>
    <br>
    <br>
    <br>
   </div>   
  <!-- aboutus box box -->	      
    <div class="cl"></div>
   </div>
  </div>
  <!-- body ends -->
