<div class="layout">
  <div class="body-outer">
    <div class="body">
   <div class="about-box">
<img src="/images/intro.png">
   <h3>Technology</h3>
<div class="row">
<div class="span8" style="font-size: 14px; font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;">

Algorithms.io is a new data infrastructure system where people can create and use algorithms and data products that are made available through a simple, credit based transactional model, that can be accessed from anywhere.
<br>
<br>
Our data infrastructure uses the latest technology stack and the power of cloud and distributed computing to make using complex algorithms and apis easier than ever before.  Create or host new algorithms or search and discover the right algorithm(s) solve your data problems, discover new insights, derive value, and power new or existing applications directly from our system.

<br>
<br>
<div class="accordion" id="accordion2">
    <div class="accordion-group">
        <div class="accordion-heading">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">What is an algorithm?</a>
        </div>
        <div id="collapseOne" class="accordion-body collapse">
            <div class="accordion-inner">
            To make a computer do anything, you have to write a computer program. To write a computer program, you have to tell the computer, step by step, exactly what you want it to do. The computer then "executes" the program, following each step mechanically, to accomplish the end goal.
When you are telling the computer what to do, you also get to choose how it's going to do it. That's where computer algorithms come in.
            </div>
        </div>
    </div>
   <div class="accordion-group">
        <div class="accordion-heading">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">What is is a data product?</a>
        </div>
        <div id="collapseTwo" class="accordion-body collapse">
            <div class="accordion-inner">
            Video
            Test
            </div>
        </div>
    </div> 
    <div class="accordion-group">
        <div class="accordion-heading">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseThree">What is a data infrastructure??</a>
        </div>
        <div id="collapseThree" class="accordion-body collapse">
            <div class="accordion-inner">
            Test
            </div>
        </div>
    </div>
     <div class="accordion-group">
        <div class="accordion-heading">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseFour">What is a transactional model?</a>
        </div>
        <div id="collapseFour" class="accordion-body collapse">
            <div class="accordion-inner">
            Test
            </div>
        </div>
    </div>
    <div class="accordion-group">
        <div class="accordion-heading">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseFive">How does the product and service work?</a>
        </div>
        <div id="collapseFive" class="accordion-body collapse">                                                                                                                                                          
            <div class="accordion-inner">                                                                                                                                                                                
            Test                                                                                                                                                                                                         
            </div>                                                                                                                                                                                                       
        </div>                                                                                                                                                                                                           
    </div>  
    <div class="accordion-group">
        <div class="accordion-heading">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseSix">What is a data science ecosystem?</a>
        </div>
        <div id="collapseSix" class="accordion-body collapse in">                                                                                                                                                          
            <div class="accordion-inner">                                                                                                                                                                                
The data science ecosystem is created by the community that uses the data infrastructure and Algorithms.io service. When data scientists and algorithm experts are armed with the appropriate tools like data infrastructure services, it makes it easier to expose the algorithms they create while providing the ability for monetization of their work.
                                                                                                                                                                                                                         
<br>                                                                                                                                                                                                                     
<br>                                                                                                                                                                                                                     
In the past this required a mass level of effort or multi-team engagements even if there were teams of experts available. Worse is that it included manually customizing mass amounts of code or having to cobble data together from a disparate amount resources simply to make something new that would be easily accessible. When it comes to big data systems or data analytics, the problem was not about what Hadoop feature or visualization engine your using, but about the algorithms, data infrastructure, and resources provided in order to obtain derive value from data or create new data products. Algorithms were wrapped around core pieces of technology within an organization, locked away with a key or only made available within libraries that had a high cost of maintenance or required general operational management principles.                                                                                            
<br><br>
By creating an ecosystem around data science, it enables others such as app developers and business users, to create new data products that can be distributed and integrated into any solution that they choose to provide and made accessible in any way they choose.                                                                                                                                                                                             
                                                                                                                                                                                                                         
<br>                                                                                                                                                                                                                     
<br>                                                                                                                                                                                                                     
The data science ecosystem we are creating, links not just the technology together, but the people involved in the process, in such a way that everything can be seen just as a service that is accessible through a transactional model.
<br>                                                                                                                                                                                                                     
<br> Algorithms.io - The Data Infrastructure For Algorithms.                
            </div>                                                                                                                                                                                                       
        </div>                                                                                                                                                                                                           
    </div>    
</div>



<br>
<br>
</p>
</div>
    <div class="span4"> 
        <address>
            <strong>Would you like access?</strong><br>
            We are currently in alpha stage and are looking for developers and data scientists that are interested in working with our system. Click the request access button below to request access.  
            <br>
            <br>
            <a href="/contact/register" class="btn btn-large btn-warning">Request Accesss</a>    
    
        </address>
    </div>
</div>
<br>
   </div>   
  <!-- aboutus box box -->	      
    <div class="cl"></div>
   </div>
  </div>
</div>
