<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Algorithms</title>
<link href="/css/style.css" rel="stylesheet" type="text/css" />
<script src="/js/html5.js" type="text/javascript"></script>
<link rel="shortcut icon" href="/images/icon.ico" type="image/x-icon">
<link rel="icon" href="/images/icon.ico" type="image/x-icon">
<!-- slider starts -->
<script type="text/javascript" src="/js/jquery-1.4.2.min.js" charset="utf-8"></script>
<script src="/js/jquery.cycle.all.min.js" type="text/javascript" charset="utf-8"></script>
<script language="javascript">
 $(document).ready(function(){
 	$('div.slides').cycle({ 
			slideExpr: 'ul.list2 li',
			fx: 'scrollLeft', // choose your transition type, ex: fade, scrollUp, shuffle, etc...
			pager: '.controls-strip',
			timeout:  0,
			pagerAnchorBuilder: function(idx, slide) { 
			myClass = (idx==0)?' class="activeSlide"':'';
			return '<a href="#" '+myClass+'></a>'; 
			}
		});
	});
 </script>
<!--/ slider ends -->
</head>
<body>
<div class="layout">
  <!-- header starts -->
  <header>
    <div class="header-inner">
      <div class="logo npl"> <a href="/index/index2"><img width="325" height="58" src="/images/logo.png" alt="logo" /></a></div>
      <div class="right-div">
            <?php
                if( ! preg_match( '/'.$this->isLoggedIn.'/', 'true' ) )
                    echo '<div class="sign-in"><a href="/login/index">Sign In </a> | <a href="/signup/index"> Register</a> </div>';
                else
                    echo '<div class="sign-in"><a href="/login/logout">Logout</a></div>';

            ?>
        <nav>
          <ul id="links">
            <li><a href="/index/index2">Home </a></li>
            <li><a href="/index/products"> Products </a></li>
            <li><a href="/index/api"> API </a></li>
            <li><a href="/index/pricing"> Pricing </a></li>
            <li><a href="/index/aboutus"> About Us</a></li>
            <li><a href="/index/jobs"> Jobs </a> </li>
          </ul>
        </nav>
      </div>
    </div>
  </header>
  <!-- header ends -->
  <!-- body starts -->
  <div class="body-outer">
    <div class="body">
  <!-- aboutus box -->	      
   <div class="about-box">
   <h3>Products</h3>
   
  <div class="products-container">
        <div class="irecommengine"><img src="/images/irecommengine-pic.jpg" alt="irecommengine-pic" /><br>
          <a href="recommengine-pricing.html"><img src="/images/get-a-price-quote.png" width="206" height="44" alt="get price quote"></a> </div>
        <div class="irecommengine no-padding"><img src="/images/algo-intelligent-faq-pic.jpg" alt="algo-intelligent-faq-pic" /> <br>
          <a href="algo-pricing.html"><img src="/images/get-a-price-quote.png" width="206" height="44" alt="get price quote"></a> </div>
        <div class="cl"></div>
      </div>
     <div class="content-div">
     <p>Nunc imperdiet nulla sit amet lorem ornare faucibus. Nullam varius tempus dui, ut euismod leo blandit at. Cras velit sapien, euismod bibendum ullamcorper sit amet, posuere et dui. Suspendisse tempor semper libero, at suscipit neque rhoncus et. Fusce sed nibh massa. Aliquam erat volutpat. Integer faucibus vulputate odio ac lacinia. Nulla tempus dictum nisl, quis condimentum lorem mollis in. Aenean fermentum posuere odio et molestie. Vivamus nec nisi lorem. Curabitur sollicitudin, nibh et tincidunt placerat, metus mauris vulputate tellus, non viverra eros velit convallis metus.</p>
     </div>
    <div class="cl"></div>
   </div>   
  <!-- aboutus box box -->	      
    <div class="cl"></div>
   </div>
  </div>
  <!-- body ends -->
  <!-- footer starts -->
  <footer>
    <div class="footer-inner">
      <div class="footer-left">
        <ul class="bottom-links">
            <li><a href="/index/index2">Home </a></li>
            <li><a href="/index/products"> Products </a></li>
            <li><a href="/index/api"> API </a></li>
            <li><a href="/index/pricing"> Pricing </a></li>
            <li><a href="/index/aboutus"> About Us</a></li>
            <li><a href="/index/jobs"> Jobs </a> </li>
        </ul>
        <br class="cl" />
        <p>&copy; Copyright 2012 algorithms.io . All Rights Reserved </p>
      </div>
    </div>
  </footer>
  <!-- footer ends -->
</div>
</body>
</html>
