<div class="container">
	
	<h1>Purchase Options:</h1>

	<div class="featurette">
        <h2 class="featurette-heading">Purchase the VMware Virtual Appliance Now. <span class="muted"></span></h2>
        <p class="lead">Once purchased, you will receive an email with the download link.  Simply download the OVA file and import it into your VMware virtual environment.</p>
        
        <p class="lead">$299 USD
        	<!--Amazon Purchase-->
			<form action="https://authorize.payments.amazon.com/pba/paypipeline" method="post">
			  <input type="hidden" name="returnUrl" value="http://www.userrobot.com/index/ova" >
			  <input type="hidden" name="processImmediate" value="1" >
			  <input type="hidden" name="accessKey" value="11SEM03K88SD016FS1G2" >
			  <input type="hidden" name="signatureMethod" value="HmacSHA256" >
			  <input type="hidden" name="collectShippingAddress" value="0" >
			  <input type="hidden" name="isDonationWidget" value="0" >
			  <input type="hidden" name="amazonPaymentsAccountId" value="QJGVHSOIJVOB1SN4DHBKZV4FF67QFXZRKNLKQA" >
			  <input type="hidden" name="cobrandingStyle" value="logo" >
			  <input type="hidden" name="immediateReturn" value="1" >
			  <input type="hidden" name="amount" value="USD 299" >
			  <input type="hidden" name="description" value="VMware Virtual Appliance.  A downloadable ova will be available after purchase." >
			  <input type="hidden" name="abandonUrl" value="http://www.userrobot.com/index/purchase" >
			  <input type="hidden" name="signatureVersion" value="2" >
			  <input type="hidden" name="signature" value="uqcz8SMT4Cl2/6X50Vx78zR0ryvf+GwJPbyiQTTHeBU=" >
			  <input type="image" src="http://g-ecx.images-amazon.com/images/G/01/asp/golden_large_paynow_withlogo_whitebg.gif" border="0">
			</form>
			
		</p>
     </div>
     
	<hr class="featurette-divider">

      <div class="featurette">
        <img class="featurette-image pull-left" src="/images/AWS_LOGO_RGB_300px.jpg">
        <h2 class="featurette-heading">Run on Amazon AWS. <span class="muted">Coming soon...</span></h2>
        <p class="lead">You will be able to purchase and spin up User Robot on Amazon AWS cloud with a few clicks of the button and start monitoring your virtual desktop environment.</p>
      </div>
      
</div>