<div class="container">
	
	<h1>Purchase Options:</h1>

	<div class="featurette">
       	<a class="wepay-widget-button wepay-green" id="wepay_widget_anchor_5112bb78ce09c" href="https://www.wepay.com/stores/812921/item/676772">Buy Now</a><script type="text/javascript">var WePay = WePay || {};WePay.load_widgets = WePay.load_widgets || function() { };WePay.widgets = WePay.widgets || [];WePay.widgets.push( {object_id: 676772,widget_type: "store_item_buy_now",anchor_id: "wepay_widget_anchor_5112bb78ce09c",widget_options: {store_id: 812921,show_item_price: true,show_item_images: true,button_text_sold_out: "Sold Out",show_item_custom_options: true,button_text: "Buy Now"}});if (!WePay.script) {WePay.script = document.createElement('script');WePay.script.type = 'text/javascript';WePay.script.async = true;WePay.script.src = 'https://static.wepay.com/min/js/widgets.v2.js';var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(WePay.script, s);} else if (WePay.load_widgets) {WePay.load_widgets();}</script>
        <h2 class="featurette-heading">Purchase the VMware Virtual Appliance Now. <span class="muted"></span></h2>
        <p class="lead">Once purchased, you will receive an email with the download link.  Simply download the OVA file and import it into your VMware virtual environment.</p>
     </div>
     
	<hr class="featurette-divider">

      <div class="featurette">
        <img class="featurette-image pull-left" src="/images/AWS_LOGO_RGB_300px.jpg">
        <h2 class="featurette-heading">Run on Amazon AWS. <span class="muted">Coming soon...</span></h2>
        <p class="lead">You will be able to purchase and spin up User Robot on Amazon AWS cloud with a few clicks of the button and start monitoring your virtual desktop environment.</p>
      </div>
      
</div>