<div class="layout">
  <div class="body-outer">
    <div class="body">
   <div class="about-box">
<img src="/images/intro.png">
   <h3>Solutions</h3>
<div class="row">
<div class="span8" style="font-size: 14px; font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;">
The Algorithms.io data infrastructure empowers individuals and businesses to work with algorithms as never before.  Use it to build powerful new applications and businesses from your data. 

<br>
<a name="companies"></a>
<br>
<div class="row">
<div  class="span1">
    <img src="/images/developers.png">
</div>
<div name="developers" class="span6" style="background: #fdbca9; padding: 20px; -moz-border-radius: 15px; border-radius: 15px;">
<div style="font-weight: bold; color:#152B4C; font-size: 18px; font-style: italic; font-family: Arial,sans-serif; margin-bottom: 10px;">Developers</div>
Stay focused on doing what you do best – create a great user experience and delight your customers.   Let us help you get the most value from your data on the back end.  Find the algorithms you need in our catalog or host your custom algorithm(s) in our data infrastructure.  Begin turning your data into added value for your application.  
<br>
<br>
<li>REST API and SDK for quick integration
<li>Easy plug-ins for popular data feeds like facebook and twitter
<li>Quickly add or modify algorithms to stay ahead of competitors
<li>Only pay for the processing power you use
<br><br>


<div id="algosExampleModal" class="modal" tabindex="1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
<a class="btn" data-toggle="modal" href="#algosExampleModal" role="button">See Examples</a>
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
              <h3 id="myModalLabel">Examples</h3>
            </div>
            <div class="modal-body">
              <img src="/images/techStack.png">
            </div>
            <div class="modal-footer">
              <a href="#" class="btn" data-dismiss="modal">Close</a>
            </div>
          </div>


</div>
</div>

<br>
<br>
<div class="row">
<div  class="span1">
<img src="/images/companies.png">
</div>
<div class="span6" style="background: #fee2a5; padding: 20px; -moz-border-radius: 15px; border-radius: 15px;">
<div style="font-weight: bold; color:#152B4C; font-size: 18px; font-style: italic; font-family: Arial,sans-serif; margin-bottom: 10px;">Tech Companies</div>
Companies building their business from data can use our infrastructure as your data science team in the cloud.  Choose from a catalog of available algorithms or let us host your unique algorithm(s) for easy access via API.  The platform can scale from MB to TB in stride with your business.  And don’t worry, we take security seriously so your “secret sauce” will be well protected.
<br>
<br>
<li>       Library of ready-to-use algorithms or use your own
<li>    Hadoop fully integrated to support big data
<li>Security roles and permissions to protect algorithms and data
<li>Pay-as-you-grow: No upfront fees, pay for what you use
<br><br><a href="#top" class="scroll">Scroll Top</a>
</div>
</div>

<br>
<a name="scientists"></a>
<br>
<div class="row">
<div  class="span1">
<img src="/images/datasci.png">
</div>
<div class="span6" style="background: #bbeaff; padding: 20px; -moz-border-radius: 15px; border-radius: 15px;">
<div style="font-weight: bold; color:#152B4C; font-size: 18px; font-style: italic; font-family: Arial,sans-serif; margin-bottom: 10px;">Data Scientists</div>
Whether you are a consultant creating custom solutions, or part of an internal data science team our solution makes it easier than ever before to develop, test, and run new algorithms.  Our visual workflow creator (coming soon) will give you the tools to create powerful new solutions in minutes.
<br>
<br>
<li>         Multi-tenant system allows you to manage multiple clients or partners
<li>       Allow your colleagues to view, explore and edit your algorithm(s).
<li>      Supports R, PHP, PIG, Hadoop, and other MapReduce environments
<li>       Customize processor and memory options to optimize performance
<br><br><a href="#top" class="scroll">Scroll Top</a>
</div>
</div>
<br>
<br>


<br>
<br>
</p>
</div>
    <div class="span4"> 
        <address>
            <strong>Would you like access?</strong><br>
            We are currently in alpha stage and are looking for developers and data scientists that are interested in working with our system. Click the request access button below to request access.  
            <br>
            <br>
            <a href="/contact/register" class="btn btn-large btn-warning">Request Accesss</a>    
    
        </address>
    </div>
</div>
<br>
   </div>   
  <!-- aboutus box box -->	      
    <div class="cl"></div>
   </div>
  </div>
</div>
