<div class="layout">
  <div class="body-outer">
    <div class="body">
   <div class="about-box">
   <h3>Technology</h3>
<div class="row">
<div class="span8" style="font-size: 14px; font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;">
Algorithms.io provides a data infrastructure stack for creating and using the algorithms and data products that power data-driven business and requires no upfront fees to get started.

<br>
<br>
The data infrastructure uses the latest technology stack and the power of cloud and distributed computing to make using complex algorithms and APIs easier than ever before. Create or host new algorithms in multiple programming languages or search and discover the right algorithm(s) to solve your data problems. Discover new insights, derive value, and power new or existing applications directly from our system. With Hadoop and other parallel programming languages and environments fully integrated the system is ready to scale with your business.

<br>
<br>
<strong>Break free from managing infrastructure.</strong>
<br>
<br><h5>The Technology Stack</h5>
<img src="/images/techStackMain.png">
<br>
<br>
<div class="accordion" id="accordion2">
    <div class="accordion-group">
        <div class="accordion-heading" style="background-color: #fdbf5b">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne"><span style="color: #c47e0d">Application Layer</span></a>
        </div>
        <div id="collapseOne" class="accordion-body collapse">
            <div class="accordion-inner">
<strong>Application Layer</strong><br>
The application layer includes a utility for data abstraction, algorithm catalog, and suite of visualizations all from a simple user interface or API/SDK.
<br>
<br>
<strong>Algorithm Catalog</strong>
<br>
The algorithm catalog enables users to discover or create new algorithms.  Each algorithm in the catalog is tagged with meta data for search and discovery.   Detailed descriptions explain how and when to use the algorithm.  Algorithm developers can create or upload new algorithms in the catalog for use by others.  The catalog sits on top of the Algorithms.io data infrastructure so algorithms can be deployed against data on the system.  All of this happens in the cloud so there are no downloads or complex code packages to deal with. It's never been easier to get more value of your data.
<br>
<br>
<strong>Integration API/SDK</strong>
An API and several SDKs are available.  You can find more information about these on our <a href="/index/docs">documentation page</a>
<br>
<br>

            </div>
        </div>
    </div>
   <div class="accordion-group">
        <div class="accordion-heading" style="background-color: #df542d">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo"><span style="color: #872307">Security Layer</span></a>
        </div>
        <div id="collapseTwo" class="accordion-body collapse">
            <div class="accordion-inner">
            The security layer enables roles and permissions to be assigned to authorized users for individual accounts. Administrators can assign multiple levels of permissions based on user needs and company security policies.  The Algorithms.io platform is multi-tenant so security for distributed teams, global user bases, and diverse partner networks can be easily managed from inside the system.  
		</div>
        </div>
    </div> 
    <div class="accordion-group">
        <div class="accordion-heading" style="background-color: #16ae57">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseThree"><span style="color:#17480a">Algorithm Runtime Environment</span></a>
        </div>
        <div id="collapseThree" class="accordion-body collapse">
            <div class="accordion-inner">
The runtime environment is built on a patent pending workflow system that enables algorithms to be chained together.  It allows both parallel and non parallel algorithms in multiple programming languages to be sequentially combined for the creation of complex algorithmic workflows.  These workflows can be run against data sets or streams to produce meaningful results or new data products. The runtime environment has native support for big data jobs on Hadoop and supports asynchronous and synchronous calls to provide results depending on your needs.
            </div>
        </div>
    </div>
     <div class="accordion-group">
        <div class="accordion-heading" style="background-color: #aad1e2">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseFour">Data Infrastructure</a>
        </div>
        <div id="collapseFour" class="accordion-body collapse">
            <div class="accordion-inner">
           The data infrastructure abstracts away the complexities involved in maintaining and managing infrastructure by automatically providing flexibility, resource management, and allocation of high performance computing clusters based on the usage of the algorithms themselves. 
<br>
<br>
In the past, building a similar solution would require significant effort or multi-team engagements.  Finding and engaging the right data team has not been easy.  Assuming a team can be created, typical solutions include manually customizing mass amounts of code or having to cobble data together from a disparate amount resources. Algorithms were wrapped around core pieces of technology within an organization, locked away with a key or only made available within libraries that had a high cost of maintenance or required general operational management principles. 

<br>
<br>
With the Algorithms.io data infrastructure organizations can focus getting the most from their data.  The required systems to begin creating and deploying algorithms have been pre-assembeled in the cloud as a service.  This "data science team in the cloud" approach allows resources to be spent on the most value added activities - modeling data and developing the right algorithms. 
	   </div>
        </div>
    </div>
    <div class="accordion-group">
        <div class="accordion-heading" style="background-color: #1991c7;">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseSix"><span style="color:#FFFFFF;">Ecosystem</span></a>
        </div>
        <div id="collapseSix" class="accordion-body collapse">                                                                                                                                                          
            <div class="accordion-inner">                                                                                                                                                                                
            Algorithms.io is building a community around algorithms.  Our platform has been designed to make it easier for data scientists, algorithm developers, application developers and business users to collaborate around algorithms to solve real problems.  

<br>
<br>
We believe in giving data scientists and algorithm experts around the world the appropriate tools to increase the pace of innovation in algorithm development.  In a world increasingly driven by data these algorithms are of fundamental importance.   

<br>
<br>
Application developers and business users bring demand for new algorithms to turn their data into value.  The data products they produce can be consumed as stand-alone products or used to explore insights and drive change. 

<br>
<br>
This ecosystem links people and technology through a platform that provides total flexibility for customization and creativity.  Request an access code and join the community today.
		</div>                                                                                                                                                                                                       
        </div>                                                                                                                                                                                                           
    </div>    
</div>



<br>
<br>
</p>
</div>
    <div class="span4">
 
<a data-toggle="modal" href="#techStackModal" role="button"><img src="/images/techStack.png"></a>
<a data-toggle="modal" href="#techStackModal" role="button">See Infrastructure</a>


<div id="techStackModal" class="modal" tabindex="1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
              <h3 id="myModalLabel">Data Infrastructure</h3>
            </div>
            <div class="modal-body">
              <img src="/images/techStack.png">
            </div>
            <div class="modal-footer">
              <a href="#" class="btn" data-dismiss="modal">Close</a>
            </div>
          </div>
        <br><br>
        <address>
            <strong>Would you like access?</strong><br>
            We are currently in alpha stage and are looking for developers and data scientists that are interested in working with our system. Click the request access button below to request access.  
            <br>
            <br>
            <a href="/contact/register" class="btn btn-large btn-warning">Request Accesss</a>    
    
        </address>
    </div>
</div>
<br>
   </div>   
  <!-- aboutus box box -->	      
    <div class="cl"></div>
   </div>
  </div>
</div>
