<?php ?>
<? require_once ('../library/AlgorithmsIO/config.php'); ?>
<? 
//$wizard_height="500px";
global $GLOBALS;
//$GLOBALS["htmllinktags"] = <<<EOS
$htmllinktags = <<<EOS
<!-- Bootstrap CSS Toolkit styles -->
<link rel="stylesheet" href="/css/fileupload/bootstrap.min.css">
<!-- Bootstrap styles for responsive website layout, supporting different screen sizes -->
<link rel="stylesheet" href="/css/fileupload/bootstrap-responsive.min.css">
<!-- Bootstrap CSS fixes for IE6 -->
<!--[if lt IE 7]><link rel="stylesheet" href="/css/fileupload/bootstrap-ie6.min.css"><![endif]-->
<!-- CSS to style the file input field as button and adjust the Bootstrap progress bars -->
<link rel="stylesheet" href="/css/fileupload/jquery.fileupload-ui.css">
<!-- Shim to make HTML5 elements usable in older Internet Explorer versions -->
<!--[if lt IE 9]><script src="/js/html5.js"></script><![endif]-->

<link rel="stylesheet" type="text/css" href="/css/flexigrid/flexigrid.pack.css" />

<link rel="stylesheet" type="text/css" href="/css/flows.css" />
<link rel="stylesheet" type="text/css" href="/css/dashboard.css" />
EOS;
#<!--[if lt IE 9]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->

$javascript = <<<EOS
<script type="text/javascript" src="/bootstrap/js/bootstrap.js"></script>
<script src="/js/algo.js"></script>
<SCRIPT src="/js/algo_dashboard.js"></SCRIPT>
<SCRIPT src="/js/jquery.json-2.3.js"></SCRIPT>
EOS;

echo pageheader(array(
	"htmllinktags"	=>$htmllinktags,
	"javascript"	=>$javascript,
        "view"          =>$this
)); 
?>
<SCRIPT>
</SCRIPT>

<DIV id="flowGrid" class="flowGrid">
<DIV id='flowMenuHolder' class='flowMenu'>
	<DIV id='flowMenuTitle' class='flowMenuTitle'>Drag a Group or Visualization</DIV>
	<ul id="draggables" style="float: left;">
            <li id="group" class="draggable group">
                <div class="removeGroup"></div>
                <ul class="widgets"></ul>
            </li>
            <li id="widget1" class="draggable widget" style="background-color: #F66;">
                <div class="removeWidget"></div>
                	<DIV id='' class='flowMenuIcon ' style="background-image: none;"></DIV>
                	<DIV class='flowMenuIconTitle'>Widget1</DIV>
            </li>
            <li id="widget2" class="draggable widget" style="background-color: #FF6;">
                <div class="removeWidget"></div>
                2
            </li>
            <li id="widget3" class="draggable widget" style="background-color: #6F6;">
                <div class="removeWidget"></div>
                3
            </li>
            <li id="widget4" class="draggable widget" style="background-color: #09C;">
                <div class="removeWidget"></div>
                4
            </li>
            <li id="widget5" class="draggable widget" style="background-color: #93F;">
                <div class="removeWidget"></div>
                5
            </li>
        </ul>

</DIV>
	<UL id="dashboard" style="float: left;"></UL>
</DIV>

<FORM><TEXTAREA id="jsonout"></TEXTAREA></FORM>
<BR><BR>
<? echo pagefooter(); ?>
