<br/>
<div class="container">
	
	<h1>Service Assurance Dashboard</h1>
	
	<a href="#newMonitorModal" role="button" class="btn btn-primary" data-toggle="modal">Add New Monitor</a>
	<a href="#newTrapModal" role="button" class="btn btn-primary" data-toggle="modal">Add New SNMP Trap Dest</a>
	
	<br/><br/>
	
	<table class="table table-striped table-bordered">
		<tr>
			<th>Monitor Name</th>
			<th>Last 24 Hours Status:<br/><?php echo $this->hourString; ?></th>
			<th>Action</th>
		</tr>
		<tr>
			<td style="width: 25%;">XenDesktop Cluster 1</td>
			<td style="width: 60%;">
				<div class="progress">
				    <div class="bar bar-success" style="width: 35%;"></div>
				    <div class="bar bar-danger" style="width: 10%;"></div>
				    <div class="bar bar-success" style="width: 35%;"></div>
				    <div class="bar bar-danger" style="width: 10%;"></div>
				    <div class="bar bar-success" style="width: 10%;"></div>
			    </div>
			</td>
			<td style="width: 15%;">
				<a href="#" rel="tooltip" title="Edit"><i class="icon-edit"></i></a>  |
				<a href="#" rel="tooltip" title="Pause"><i class="icon-pause"></i></a>  |
				<a href="#" rel="tooltip" title="Delete"><i class="icon-remove"></i></a>
			</td>
		</tr>
		<tr>
			<td>XenDesktop Cluster 2</td>
			<td>
				<div class="progress">
					<div class="bar bar-success" style="width: 100%;"></div>
				</div>
			</td>
			<td>
				<a href="#" rel="tooltip" title="Edit"><i class="icon-edit"></i></a>  |
				<a href="#" rel="tooltip" title="Pause"><i class="icon-pause"></i></a>  |
				<a href="#" rel="tooltip" title="Delete"><i class="icon-remove"></i></a>
			</td>
		</tr>
		<tr>
			<td>XenDesktop Cluster 3</td>
			<td>
				<div class="progress">
					<div class="bar bar-success" style="width: 100%;"></div>
				</div>
			</td>
			<td>
				<a href="#" rel="tooltip" title="Edit"><i class="icon-edit"></i></a>  |
				<a href="#" rel="tooltip" title="Pause"><i class="icon-pause"></i></a>  |
				<a href="#" rel="tooltip" title="Delete"><i class="icon-remove"></i></a>
			</td>
		</tr>
		<tr>
			<td>XenDesktop Cluster 4</td>
			<td>
				<div class="progress">
					<div class="bar bar-success" style="width: 100%;"></div>
				</div>
			</td>
			<td>
				<a href="#" rel="tooltip" title="Edit"><i class="icon-edit"></i></a>  |
				<a href="#" rel="tooltip" title="Pause"><i class="icon-pause"></i></a>  |
				<a href="#" rel="tooltip" title="Delete"><i class="icon-remove"></i></a>
			</td>
		</tr>
	</table>
</div>


<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<!-- Modal New Monitor-->
<div id="newMonitorModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		<h3 id="myModalLabel">Add New XenDesktop Monitor</h3>
	</div>
	<form>
		<div class="modal-body">
			<legend>Test Parameters</legend>
			<fieldset>
				<label>Host Name:</label>
				<input type="text" placeholder="vdi.example.com">
				<label>Domain Name:</label>
				<input type="text" placeholder="example.com">
				<label>User Name:</label>
				<input type="text" placeholder="Mike">
				<label>Password:</label>
				<input type="text" placeholder="Mike's Password">
			</fieldset>
		</div>
		<div class="modal-footer">
			<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
			<button class="btn btn-primary">Save changes</button>
		</div>
	</form>
</div>
<!-- Modal New Trap Destination-->
<div id="newTrapModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		<h3 id="myModalLabel">Add New SNMP Trap Destination</h3>
	</div>
	<form>
		<div class="modal-body">
			<legend>Test Parameters</legend>
			<fieldset>
				<label>Trap Name:</label>
				<input type="text" placeholder="Production Trap Server">
				<label>Trap Destination:</label>
				<input type="text" placeholder="trap.example.com">
			</fieldset>
		</div>
		<div class="modal-footer">
			<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
			<button class="btn btn-primary">Save changes</button>
		</div>
	</form>
</div>
