<br/>
<div class="container">
	
	<h1>Dashboard</h1>
	
	<a href="#newXenDesktopMonitorModal" role="button" class="btn btn-primary" data-toggle="modal">Add New XenDesktop Monitor</a>
	<a href="#newAPIRestMonitorModal" role="button" class="btn btn-primary" data-toggle="modal">Add New API REST Monitor</a>
	<a href="/notify/index" role="button" class="btn btn-primary" data-toggle="modal">Notifications</a>
	
	<br/><br/>
	

	
	<table class="table table-striped table-bordered">
		<tr>
			<th>Monitor Name</th>
			<th>Last 24 Hours Status:<br/><?php //echo $this->hourString; ?></th>
			<th>Actions</th>
		</tr>
		
		<?php
		
			// Outputting each Monitor
			foreach($this->monitorStatuses as $aMonitor){
				
				echo '<tr>';
					echo '<td style="width: 25%;"><a href="/dashboard/details/monitor/'.$aMonitor['monitor_id'].'/duration/24h/name/'.$aMonitor['monitor_name'].'">'.$aMonitor['monitor_name'].'</a></td>';
					echo '<td style="width: 42%;">';
						echo '<div class="progress">';
						
							// Outputting each monitors test result
							foreach($aMonitor['results']['data'] as $aDataPoint){
								
								// Good
								if($aDataPoint['status'] == 1)
									echo '<div class="bar bar-success" style="width: '.$aMonitor['results']['percentage_slices'].'%;" rel="tooltip" title="'.$aDataPoint['created'].'"></div>';
								// bad
								if($aDataPoint['status'] == -1)
									echo '<div class="bar bar-danger" style="width: '.$aMonitor['results']['percentage_slices'].'%;" rel="tooltip" title="'.$aDataPoint['created'].'"></div>';
								// unknown
								if($aDataPoint['status'] == 0)
									echo '<div class="bar bar-warning" style="width: '.$aMonitor['results']['percentage_slices'].'%;" rel="tooltip" title="'.$aDataPoint['created'].'"></div>';
							}
					    echo '</div>';
					echo '</td>
					<td style="width: 15%;">
						<a href="/monitor/edit/id/'.$aMonitor['monitor_id'].'" rel="tooltip" title="Edit"><i class="icon-edit"></i></a>  |';
						
						// Pause functionality
						if($aMonitor['monitor_is_active']==1)
							echo '<a href="/monitor/pause/id/'.$aMonitor['monitor_id'].'" rel="tooltip" title="Pause"><i class="icon-pause"></i></a>  |';
						else
							echo '<a href="/monitor/unpause/id/'.$aMonitor['monitor_id'].'" rel="tooltip" title="Enable"><i class="icon-play"></i></a>  |';
						echo '<a href="/monitor/delete/id/'.$aMonitor['monitor_id'].'" rel="tooltip" title="Delete"><i class="icon-remove"></i></a>
					</td>';
				echo '</tr>';
			}
		
		?>

	</table>
</div>


<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<!-- Modal New XenDesktop Monitor-->
<div id="newXenDesktopMonitorModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		<h3 id="myModalLabel">Add New XenDesktop Monitor</h3>
	</div>
	<form method="post" action="/monitor/xendesktop/action/save">
		<input type="hidden" name="ac" value="save"/>
		<div class="modal-body">
			<legend>XenDesktop Parameters</legend>
			<fieldset>
				<label>Monitor Name:</label>
				<input type="text" name="name" placeholder="Production - vdi.example.com">
				<label>Host Name:</label>
				<input type="text" name="baseURL" placeholder="vdi.example.com">
				<label>Domain Name:</label>
				<input type="text" name="domain" placeholder="example.com">
				<label>User Name:</label>
				<input type="text" name="username" placeholder="Test User login">
				<label>Password:</label>
				<input type="text" name="password" placeholder="Test User Password">
				<label>Version:</label>
				<input type="text" name="version" placeholder="5.6">
				<label>Test Interval in Minutes:</label>
				<input type="text" name="schedule" placeholder="1">
				<label>Notification Destination:</label>
				<select name="notification_id">
					<?php  
						foreach($this->notificationList as $aNotification){
							echo '<option value="'.$aNotification['id'].'">'.$aNotification['name'].'</option>';
						}
					?>
				</select>
			</fieldset>
		</div>
		<div class="modal-footer">
			<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
			<button class="btn btn-primary">Save changes</button>
		</div>
	</form>
</div>
<!-- Modal New Trap Destination-->
<div id="newTrapModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		<h3 id="myModalLabel">Add New Email Destination</h3>
	</div>
	<form action="/notify/emailsave" method="post">
		<div class="modal-body">
			<legend>Email Parameters</legend>
			<fieldset>
				<label>Notifiation Name:</label>
				<input type="text" name="name" placeholder="My Email Notification">
				<label>Use Athentication:</label>
				<select name="is_authenticated">
					<option value="true">True</option>
					<option value="false">False</option>
				</select>
				<label>Authentication User</label>
				<input type="text" name="authUser" placeholder="User: if use auth is true">
				<label>Authentication Password</label>
				<input type="text" name="authPassword" placeholder="Password: if use auth is true">
				<label>SMTP Address</label>
				<input type="text" name="smtp" placeholder="mail.example.com">
				<label>From Email</label>
				<input type="text" name="fromEmail" placeholder="From Email Address">
				<label>To Email</label>
				<input type="text" name="toEmail" placeholder="Email to send to">
				<label>Subject Prefix</label>
				<input type="text" name="subject_prefix" placeholder="Subject prefix">
				<label>Domain</label>
				<input type="text" name="domain" placeholder="example.com">
			</fieldset>
		</div>
		<div class="modal-footer">
			<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
			<button class="btn btn-primary">Save</button>
		</div>
	</form>
</div>
<!-- Modal New API REST Monitor-->
<div id="newAPIRestMonitorModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		<h3 id="myModalLabel">Add New API REST Monitor</h3>
	</div>
	<form method="post" action="/monitor/apirest/action/save">
		<input type="hidden" name="ac" value="save"/>
		<div class="modal-body">
			<legend>API REST Parameters</legend>
			<fieldset>
				<label>Monitor Name:</label>
				<input type="text" name="name" placeholder="Production - vdi.example.com">
				<label>Notification Destination:</label>
				<select name="notification_id">
					<?php  
						foreach($this->notificationList as $aNotification){
							echo '<option value="'.$aNotification['id'].'">'.$aNotification['name'].'</option>';
						}
					?>
				</select>
				<label>Test Interval in Minutes:</label>
				<input type="text" name="schedule" placeholder="1">
				
				<!-- Monitor Specific Inputs-->
				<label>Endpoint URL:</label>
				<input type="text" name="url" placeholder="my-api.example.com">
				<label>Post Params:</label>
				<textarea name="post_params" rows="6" cols="10" placeholder="{&quot;parm_1&quot;:&quot;value&quot;,&quot;param_1&quot;:&quot;value&quot;}"></textarea>
				<label>Header Params:</label>
				<textarea name="headers" rows="6" cols="10" placeholder="[&quot;authToken: 12344&quot;, &quot;Content-Type: json&quot;]"></textarea>
				<label>Regex Search:</label>
				<input type="text" name="regex_check" placeholder="^starts with something">
			</fieldset>
		</div>
		<div class="modal-footer">
			<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
			<button class="btn btn-primary">Save changes</button>
		</div>
	</form>
</div>
