<?php ?>
<? //require_once realpath(dirname(__FILE__).'/inc/config.php'); ?>
<? require_once ('AlgorithmsIO/config.php'); ?>
<? 

//$wizard_height="500px";
global $GLOBALS;
//$GLOBALS["htmllinktags"] = <<<EOS
$htmllinktags = <<<EOS
<!-- Bootstrap CSS Toolkit styles -->
<link rel="stylesheet" href="/css/fileupload/bootstrap.min.css">
<!-- Bootstrap styles for responsive website layout, supporting different screen sizes -->
<link rel="stylesheet" href="/css/fileupload/bootstrap-responsive.min.css">
<!-- Bootstrap CSS fixes for IE6 -->
<!--[if lt IE 7]><link rel="stylesheet" href="/css/fileupload/bootstrap-ie6.min.css"><![endif]-->
<!-- CSS to style the file input field as button and adjust the Bootstrap progress bars -->
<link rel="stylesheet" href="/css/fileupload/jquery.fileupload-ui.css">
<!-- Shim to make HTML5 elements usable in older Internet Explorer versions -->
<!--[if lt IE 9]><script src="/js/html5.js"></script><![endif]-->

<link rel="stylesheet" type="text/css" href="/css/flexigrid/flexigrid.pack.css" />
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.9.0.custom.css" />                
<link rel="stylesheet" type="text/css" href="/css/flows.css" />
EOS;
#<!--[if lt IE 9]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->

//$API_JS = $this->API_URL."js/AlgorithmsIO_API.js";
$API_JS = $this->API_URL."Jssdk/?authToken=".$this->token;

$javascript = <<<EOS
<script src="/js/bootstrap-tab.js"></script>
<script type="text/javascript" src="$API_JS"></script> 
<script type="text/javascript" src="/js/tiny_mce/jquery.tinymce.js"></script>    
<script src="/js/algo.js"></script>
<SCRIPT src="/js/algo_flows.js"></SCRIPT>
<SCRIPT src="/js/jsPlumb/jquery.jsPlumb-1.3.11-all-min.js"></SCRIPT>
<SCRIPT src="/js/algo_mapper.js"></SCRIPT>
EOS;

echo pageheader(array(
	"htmllinktags"	=>$htmllinktags,
	"javascript"	=>$javascript,
        "nav_tab"       =>"workflows",    
        "view"          =>$this
)); 
?>
<SCRIPT>
var myFlowGrid;
$(function (){
        var myAjaxError = function(jqXHR, textStatus, errorThrown) {
          console.log(jqXHR);
          console.log(textStatus);
          console.log(errorThrown);
          alert("ERROR201209101138: "+errorThrown);
        };
        var myAjaxSuccess = function(result) {
            myFlowGrid.setFlowId(result['id']);
            //console.log(result);
            //console.log("^^^^^^^^^^^^^^^^^^^^^^^^^^^^^");
            //alert("Success"+result);
        }
        var flowSaveCallback = function(flowGrid, json) {
            
            
            var data = {
                id:           flowGrid.getFlowId(),
                name:         flowGrid.mydata["name"],
                description:  flowGrid.mydata["description"],
                details:      flowGrid.mydata["details"],
                hidden_workflow: flowGrid.mydata["hidden_workflow"],
                type:         "JSON_Flow",
                version:      "0.1",
                flowData:     JSON.parse(json), // Seems silly I know
            };
            console.log("DEBUG201208151911: flowSave Outgoing: ");
            console.log(data);
            $.ajax({
                type:       'POST',
                dataType:   'json',
                //crossDomain:  true,
                url:        "<?=$this->API_URL."flows/";?>?authToken=<?=$this->token;?>&ts="+(0+new Date().getTime()),
                //headers:    {"authToken": "<?=$this->token;?>"},
                success:    myAjaxSuccess,
                error:      myAjaxError,
                data:       {
                                api_version:  "0.1",
                                api_call: JSON.stringify(data)
                            },
            })
        };
        var flowGetJSON = function(id) {
            console.log("DEBUG201208161723: Retrieving flow "+id);
            $.ajax({
              url: '<?=$this->API_URL."flows/id/";?>'+id+'?authToken=<?=$this->token;?>&ts="+(0+new Date().getTime())',
              dataType: 'json',
              //data: data,
              success: startMyFlowGrid,
            });
        }
        //var fakeJSON = '[{"type":"Placeholder","gridX":4,"gridY":0,"uuid":"ef758658-bfd0-4e62-a361-243295285988","nextUUID":"","previousUUID":"997b64ba-b0e4-44d6-bad7-23938ea29255"},{"type":"Stream","gridX":0,"gridY":0,"uuid":"1217d71e-fc08-4fbb-be6f-5157f6dc3f5b","nextUUID":"a6002e5a-953b-4498-8d26-c33d1793bb9a","previousUUID":""},{"type":"Filter","gridX":1,"gridY":0,"uuid":"a6002e5a-953b-4498-8d26-c33d1793bb9a","nextUUID":"b5301a6d-d1a3-4e27-a8ee-8c64b4ad5dea","previousUUID":"1217d71e-fc08-4fbb-be6f-5157f6dc3f5b"},{"type":"Interface","gridX":2,"gridY":0,"uuid":"b5301a6d-d1a3-4e27-a8ee-8c64b4ad5dea","nextUUID":"997b64ba-b0e4-44d6-bad7-23938ea29255","previousUUID":"a6002e5a-953b-4498-8d26-c33d1793bb9a"},{"type":"Merge","gridX":3,"gridY":0,"uuid":"997b64ba-b0e4-44d6-bad7-23938ea29255","nextUUID":"ef758658-bfd0-4e62-a361-243295285988","previousUUID":"b5301a6d-d1a3-4e27-a8ee-8c64b4ad5dea"}]';
        var gridPlumb = jsPlumb.getInstance();        
        var startMyFlowGrid = function(response) {
            console.log(response);
            var flowDataJSON = response["flow_data"];
            console.log(flowDataJSON);
            myFlowGrid = new flowGrid($('#flowGrid'), {
                mydata:         response,
                flowid:         response["id"],
                JSON:           flowDataJSON,
                saveCallback:   flowSaveCallback,
                gridPlumb:      gridPlumb
            });
            myFlowGrid.setup();
            //myFlowGrid.addFromJSON(fakeJSON);
        }
 <? if(isset($this->params['id'])) { ?>     
        flowGetJSON(<?=$this->params['id'];?>);
 <? } else { ?>
        myFlowGrid = new flowGrid($('#flowGrid'), {
           saveCallback:        flowSaveCallback, 
        });
        myFlowGrid.setup();
 <? } ?>
        
	$('.wizardBox').center().hide();
        $('#div_datasources_list').hide();
        $('#div_algorithms_list').hide();
        $('#div_mapper').hide();

        //$('#flowMenuTitle').css("border", "5px solid red");
        //$('#flowMenuTitle').click(function() { alert('hi'); showWizardPopup($('#div_flowProperties'));}).css("border", "5px solid red");
    $( "#properties_tabs" ).tabs({
    });            
});

function restoreFlowGridDiv(fadeOutObj) {
    $(fadeOutObj).fadeOut('slow');
    //$('#flowGrid_container').delay(800).fadeIn('slow');
    removeBlackOut();
}

function showWizardPopup(fadeInObj, callback) {
    blackOut();
    if(typeof callback !== "function") {
        console.log("Typeof"+typeof callback);
        callback = function () {/* No Callback Do Nothing */};
    }
    //fadeInObj.center();
    //$('#flowGrid_container').fadeOut('slow'); 
    $(fadeInObj).center().delay(800).fadeIn('slow', callback);
}

function startJob() {
    if(myFlowGrid.getFlowId()) {
        //TODO: Should check if we are dirty, and not allow a startJob until we are saved.
        window.location = "/jobs/?flow_id="+myFlowGrid.getFlowId();
    } else {
        alert("ERROR201209101341: Please make sure your workflow has been saved and validated before running as a job.");
    }
}
</SCRIPT>
<!-- <video id="backgroundVideo" preload="metadata" loop="" autoplay="" style="display: block; visibility: visible; min-height: 576px; min-width: 980px; top: 0px; left: 0px; position: absolute; height: auto; width: 100%; " src="http://www.maerskfleet.com/media/video/2_M_tanker.theora.ogv"></video>  -->
<div id="flowGrid_Shell" style="min-height: 500px">
    <div id="flowGrid_container">
        <div id="button_container" style="margin-left: 5px;">
            <div class="button-general"><a href="javascript:void(0);" onclick="myFlowGrid.save();"><img src="/images/glyphicons/glyphicons_232_cloud_white.png" class="button-general-icon"><?=$this->localization->buttons->SaveAlgorithmtext; ?></a></div>
            <div class="button-spacer"></div>
            <div class="button-general disabled"><a href="/ide/index" zonclick="startWizard();"><img src="/images/glyphicons/glyphicons_193_circle_ok_white.png" class="button-general-icon"><?=$this->localization->buttons->ValidateAlgorithmtext; ?></a></div>
            <div class="button-spacer"></div>
            <div id="button_modifyAlgorithm" class="button-general"><a href="javascript:void(0);" onclick="startJob();"><img src="/images/glyphicons/MRR_Round_Play_white.png" class="button-general-icon"><?=$this->localization->IDE->buttons->StartJobtext; ?></a></div> 
        </div>
        <BR clear=all> <BR clear=all>

        <DIV id="flowGrid" class="flowGrid" zstyle="width:100%; min-height: 600px; height: 80%; overflow: auto;">
        </DIV>
    </div> <!-- End flowGrid_container -->
</div>
<DIV id="notaflowGrid">
</DIV>

<DIV id="div_datasources_list" class="wizardBox" style="min-height: 550px;" zstyle="border: 5px solid red;">
    <h2><? echo $this->localization->IDE->DataSources->DataSourceListTitle; ?></h2>
    <? include_once("datasources_list.php"); ?>
    <div id="button_datasource_close" class="button-cancel disabled" style="float: right;"><a href="javascript:void(0);" onclick="restoreFlowGridDiv($('#div_datasources_list'));"><?=$this->localization->buttons->closetext; ?></a></div>
</div>

<DIV id="div_algorithms_list" class="wizardBox" style="min-height: 550px;" zstyle="border: 5px solid red;">
    <h2><? echo $this->localization->IDE->Algorithms->AlgorithmsListTitle; ?></h2>
    <? include_once("algorithms_list.php"); ?>
    <div id="button_algorithms_close" class="button-cancel disabled" style="float: right;"><a href="javascript:void(0);" onclick="restoreFlowGridDiv($('#div_algorithms_list'));"><?=$this->localization->buttons->closetext; ?></a></div>
</div>

<DIV id="div_visualizations_list" class="wizardBox" style="min-height: 550px; overflow: auto;" zstyle="border: 5px solid red;">
    <h2><? echo $this->localization->Flows->Visualizations->Properties->Title; ?></h2>
    <? include_once("visualizations_list.php"); ?>
    <div id="button_visualization_close" class="button-cancel disabled" style="float: right;"><a href="javascript:void(0);" onclick="restoreFlowGridDiv($('#div_visualizations_list'));"><?=$this->localization->buttons->closetext; ?></a></div>
</div>

<DIV id="div_mapper" class="wizardBox" style="min-height: 550px;" zstyle="border: 5px solid red;">
    <h2><? echo $this->localization->IDE->Mapper->MapperTitle; ?></h2>
    <BR><BR>
    <? echo $this->localization->IDE->Mapper->MapperInstructions; ?><BR><BR>
    <? include_once("mapper.php"); ?>
    <div id="button_mapper_close" class="button-cancel disabled" style="float: right;"><a href="javascript:void(0);" onclick="restoreFlowGridDiv($('#div_mapper'));"><?=$this->localization->buttons->closetext; ?></a></div>
</div>

<DIV id="div_flowProperties" class="wizardBox" style="min-height: 550px;" zstyle="border: 5px solid red;">
    <h2><? echo $this->localization->Flows->IDE->Properties->Title; ?></h2>
    <BR><BR>
    <? echo $this->localization->Flows->IDE->Properties->Instructions; ?><BR><BR>
    <? include_once("flowProperties.php"); ?>
    <div id="button_properties_close" class="button-cancel disabled" style="float: right;"><a href="javascript:void(0);" onclick="closeFlowProperties(myFlowGrid);"><?=$this->localization->buttons->closetext; ?></a></div>
</div>
<BR><BR>
<? echo pagefooter(); ?>
