<br/>
<div class="container">
	
	<h1>Notifications</h1>
	
	<a href="#newTrapModal" role="button" class="btn btn-primary" data-toggle="modal">Add New Email Destination</a>
	
	<br/><br/>
	

	
	<table class="table table-striped table-bordered">
		<tr>
			<th>Notification Name</th>
			<th>Actions</th>
		</tr>
		
		<?php
		
			// Outputting each Monitor
			foreach($this->notifications as $aRow){
				
				echo '<tr>';
					echo '<td style="width: 25%;">'.$aRow['name'].'</td>';
					
					echo '</td>
					<td style="width: 15%;">
						<!--<a href="#" rel="tooltip" title="Edit"><i class="icon-edit"></i></a>  |-->';
						
						// Edit
						echo '<a href="/notify/edit/id/'.$aRow['id'].'" rel="tooltip" title="Edit"><i class="icon-edit"></i></a> | ';
						// Delete
						echo '<a href="/notify/delete/id/'.$aRow['id'].'" rel="tooltip" title="Delete"><i class="icon-remove"></i></a>
					</td>';
				echo '</tr>';
			}
		
		?>

	</table>
</div>


<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>

<!-- Modal New Trap Destination-->
<div id="newTrapModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		<h3 id="myModalLabel">Add New Email Destination</h3>
	</div>
	<form action="/notify/emailsave" method="post">
		<div class="modal-body">
			<legend>Email Parameters</legend>
			<fieldset>
				<label>Notifiation Name:</label>
				<input type="text" name="name" placeholder="My Email Notification">
				<label>Use Athentication:</label>
				<select name="is_authenticated">
					<option value="true">True</option>
					<option value="false">False</option>
				</select>
				<label>Authentication User</label>
				<input type="text" name="authUser" placeholder="User: if use auth is true">
				<label>Authentication Password</label>
				<input type="text" name="authPassword" placeholder="Password: if use auth is true">
				<label>SMTP Address</label>
				<input type="text" name="smtp" placeholder="mail.example.com">
				<label>From Email</label>
				<input type="text" name="fromEmail" placeholder="From Email Address">
				<label>To Email</label>
				<input type="text" name="toEmail" placeholder="Email to send to">
				<label>Subject Prefix</label>
				<input type="text" name="subject_prefix" placeholder="Subject prefix">
				<label>Domain</label>
				<input type="text" name="domain" placeholder="example.com">
			</fieldset>
		</div>
		<div class="modal-footer">
			<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
			<button class="btn btn-primary">Save</button>
		</div>
	</form>
</div>
