<? // login/index.phtml ?>
<? //echo $this->form ?>

<script language="javascript">
 $(document).ready(function(){
     
    $("#password").keyup(function(event){
        if(event.keyCode == 13){
            $('#form_login').submit();
        }
    });

    $("#username").keyup(function(event){
        if(event.keyCode == 13){
            $('#password').focus();
        }
    });
});



 </script>
  <!-- body starts -->
  <div class="body-outer">
    <div class="body">
    <div class="loginbody">
    <h1><? if(getenv('APPLICATION_ENV') != "production") { echo strtoupper(getenv('APPLICATION_ENV'))." "; } ?>Forgot Password?</h1>
    <BR>
    <form id="form_login" enctype="application/x-www-form-urlencoded" action="/login/forgotpass" method="post">
        <div class="loginbox">
            <div class="form">
                <div class="row">
                        <dt id="username-label"><label for="email" class="required" style="white-space: nowrap;">Email:</label></dt>
                        <dd id="username-element">
                        <input type="text" name="username" id="email" value="" /></dd>
                        <div class="cl"></div>
                <div class="cl"></div>
            </div>
            <div class="row2" style="padding: 0px;">
                    <div class="button-spacer"></div>
                    <div class="button-spacer"></div>
                    <div class="button-spacer"></div>
                    <a class="btn btn-large btn-primary" href="javascript:void(0);" onclick="$('#form_login').submit();">Get Temporary Password</a>
                    <div class="button-spacer"></div>
                    
            <div class="cl"></div>                                                                                           
        </div>                                                                                                           
    </form>

     </div>
     <div class="newregister">
     <h4>are you a new member?</h4>
     <span>Signup today and get free credits to run Algorithms</span>
     <a class="btn btn-large btn-primary" href="/signup">Register Now</a>
     </div>
     <div class="cl"></div>
     </div>
     </div>
      <div class="cl"></div>
    </div>
      <BR><BR><BR>
  </div>
