<? // login/index.phtml ?>
<? //echo $this->form ?>

  <div class="body-outer">
    <div class="body">
    <div class="loginbody">
    <form id="contact_us" action="/contact/" method="post">
    <h1>Thanks for contacting us!</h1>
    <BR>

We will be sending further responses to <? echo $this->email; ?>
</div>
     <div class="cl">
    </div>
     </div>
     </div>
      <div class="cl"></div>
    </div>
      <BR><BR>
    </form>
  </div>
