<? // login/index.phtml ?>
<? //echo $this->form ?>

  <div class="body-outer">
    <div class="body">
    <div class="loginbody">
    <form id="register" action="/contact/confirm" method="post">
    <h3>I want more information or need support.  Please contact me.  You can always send an email to support@userrobot.com.</h3>
    <BR>
    <input type="hidden" name="register" value="1">
        <div class="loginbox">
            <div class="form">
                <div class="row">
                        <dt id="username-label"><label for="name" class="required">Full Name:</label></dt>
                        <dd id="username-element">
                        <input type="text" name="name" id="name" value="" /></dd>
                        <div class="cl"></div>

                        <dt id="username-label"><label for="email" class="required">Email:</label></dt>
                        <dd id="username-element">
                        <input type="text" name="email" id="email" value="" /></dd>
                        <div class="cl"></div>

                        <dt id="username-label"><label for="company" class="required">Company:</label></dt>
                        <dd id="username-element">
                        <input type="text" name="company" id="company" value="" /></dd>
                        <div class="cl"></div>

                        <dt id="username-label"><label for="phone" class="required">Phone:</label></dt>
                        <dd id="username-element">
                        <input type="text" name="phone" id="phone" value="" /></dd>
                        <div class="cl"></div>
                        
                        

                <div class="cl"></div>
            </div>


            <div style="padding-left: 80px">
                <a class="btn btn-large btn-warning" href="javascript:void(0);" onclick="$('#register').submit();">Submit Info</a>
                <BR><BR>
            <div class="cl"></div>    
        </div>                                                                                                           

     </div>
<div class="newregister"> 
<dt id="username-label"><label>Anything else you'd like us to know?</label></dt>
<textarea name="info" rows="10" style="width: 350px" name="info"></textarea>

</div>
     <div class="cl">
    </div>
     </div>
     </div>
      <div class="cl"></div>
    </div>
      <BR><BR>
    </form>
  </div>
