<?php 

$libraries = array();

//$csv = str_getcsv(file_get_contents('/tmp/R_libs.csv'));
$counter=0;
//echo getcwd();

$file = fopen('../application/views/scripts/viside/JS_libs.csv', 'r');
while ((($csvline = fgetcsv($file)) !== FALSE) && ($counter < 50)) {
  //$line is an array of the csv elements
  //$csv[]=$csvline;
  $libraries[]=array(
        "data"      =>$csvline[1],
        "metadata"  =>array("description"=>$csvline[2]),
      );
  $counter++;
}
fclose($file);

//print_r($csv);
$encaps = array(
    "data"          =>"libraries",
    "children"      =>$libraries,
);
echo json_encode($encaps);
//echo json_encode($libraries); 
?>