<?php ?>
<? //require_once realpath(dirname(__FILE__).'/inc/config.php'); ?>
<? require_once ('AlgorithmsIO/config.php'); ?>
<? 
//$wizard_height="500px";
global $GLOBALS;

$htmllinktags = <<<EOS
<!-- Shim to make HTML5 elements usable in older Internet Explorer versions -->
<!--[if lt IE 9]><script src="/js/html5.js"></script><![endif]-->

<link rel="stylesheet" type="text/css" href="/css/flexigrid/flexigrid.pack.css" />
<link rel="stylesheet" href="/js/codemirror/codemirror.css">

<link rel="stylesheet" type="text/css" href="/css/layouts/viside_layout.css" />
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.9.0.custom.css" />
EOS;
#<!--[if lt IE 9]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->

$API_JS = $this->API_URL."Jssdk/?authToken=".$this->token;
$javascript = <<<EOS
<!-- BEGIN: Layout Stuff -->
<script type="text/javascript" src="/js/jquery.layout-latest.js"></script>
<script type="text/javascript" src="/lib/js/jquery.layout.resizePaneAccordions-1.0.js"></script>
<script type="text/javascript" src="/js/complex.js"></script>
<script type="text/javascript" src="/js/jquery-layout-debug.js"></script>
<!-- END: Layout Stuff -->   

<script type="text/javascript" src="$API_JS"></script> 
<script src="/js/bootstrap-tab.js"></script>
<script src="/js/jquery.jstree/jquery.jstree.js"></script>
<script src="/js/algo.js"></script>
<script src="/js/codemirror/codemirror.js"></script>
<script src="/js/codemirror/mode/javascript/javascript.js"></script>
<script src="/js/VisualizationIDE.js"></script>
<script src="/js/jquery.timeago.js"></script>
EOS;

echo pageheader(array(
	"htmllinktags"	=>$htmllinktags,
	"javascript"	=>$javascript,
        "body_css"      =>"max", // Break out of the template width bindings
        "nav_tab"       =>"visualizations",    
        "view"          =>$this,
        "skip_body"     =>true,
        "header_off"    =>true,
)); 
?>
<div zclass="ui-layout-east" style="height: 500px; border: 1px solid #0f0;">

	<div class="header">Outer - East</div>

	<div class="subhead">I'm a subheader</div>

	<div class="content" style="height: 100%;">
                    <div id="accordion2" class="basic">

			<h3><a href="#">Section 1</a></h3>
			<div id="divtest" style="border: 1px solid #f0f;">
				<p>Mauris mauris ante, blandit et, ultrices a, suscipit eget, quam. 
					Integer ut neque. Vivamus nisi metus, molestie vel, gravida in, condimentum sit amet, nunc.</p>
				<p>Nam a nibh. Donec suscipit eros. Nam mi. Proin viverra leo ut odio. Curabitur malesuada. 
					Vestibulum a velit eu ante scelerisque vulputate.</p>
			</div>

			<h3><a href="#">Section 2</a></h3>
			<div>
				<h5>Sed Non Urna</h5>
				<p>Donec et ante. Phasellus eu ligula. Vestibulum sit amet purus.
					Vivamus hendrerit, dolor at aliquet laoreet, mauris turpis porttitor velit,
					faucibus interdum tellus libero ac justo.</p>
				<p>Vivamus non quam. In suscipit faucibus urna.</p>
			</div>

			<h3><a href="#">Section 3</a></h3>
			<div>
				<p>Nam enim risus, molestie et, porta ac, aliquam ac, risus. Quisque lobortis.
					Phasellus pellentesque purus in massa. Aenean in pede.</p>
				<p>Phasellus ac libero ac tellus pellentesque semper. Sed ac felis. Sed commodo, 
					magna quis lacinia ornare, quam ante aliquam nisi, eu iaculis leo purus venenatis dui.</p>
				<ul>
					<li>List item one</li>
					<li>List item two</li>
					<li>List item three</li>
				</ul>
			</div>

			<h3><a href="#">Section 4</a></h3>
			<div>
				<p>Cras dictum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames 
					ac turpis egestas.</p>
				<p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;
					Aenean lacinia mauris vel est.</p>
				<p>Suspendisse eu nisl. Nullam ut libero. Integer dignissim consequat lectus.
					Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</p>
			</div>

		</div>
<!--                
		<ul id="createInner">
			<li><a href="#" onClick="createInnerLayout(); return false;">CREATE Inner Layout</a></li>
		</ul>
		<ul id="innerCommands" style="display: none;">
			<li><a href="#" onClick="innerLayout.toggle('north')">Toggle North</a></li>
			<li><a href="#" onClick="innerLayout.toggle('south')">Toggle South</a></li>
			<li><a href="#" onClick="innerLayout.toggle('west')"> Toggle West</a></li>
			<li><a href="#" onClick="innerLayout.toggle('east')"> Toggle East</a></li>
			<li><a href="#" onClick="innerLayout.hide('north')">Hide North</a></li>
			<li><a href="#" onClick="innerLayout.hide('south')">Hide South</a></li>
			<li><a href="#" onClick="innerLayout.hide('west')"> Hide West</a></li>
			<li><a href="#" onClick="innerLayout.hide('east')"> Hide East</a></li>
			<li><a href="#" onClick="innerLayout.show('east')"> Show East</a></li>
			<li><a href="#" onClick="innerLayout.sizePane('north', 50); innerLayout.open('north')">   Resize North=50</a></li>
			<li><a href="#" onClick="innerLayout.sizePane('north', 300); innerLayout.open('north')">  Resize North=300</a></li>
			<li><a href="#" onClick="innerLayout.sizePane('north', 10000); innerLayout.open('north')">Resize North=10000</a></li>
			<li><a href="#" onClick="innerLayout.sizePane('south', 50); innerLayout.open('south')">   Resize South=50</a></li>
			<li><a href="#" onClick="innerLayout.sizePane('south', 300); innerLayout.open('south')">  Resize South=300</a></li>
			<li><a href="#" onClick="innerLayout.sizePane('south', 10000); innerLayout.open('south')">Resize South=10000</a></li>
			<li><a href="#" onClick="innerLayout.panes.north.css('backgroundColor','#FCC')">North Color = Red</a></li>
			<li><a href="#" onClick="innerLayout.panes.north.css('backgroundColor','#CFC')">North Color = Green</a></li>
			<li><a href="#" onClick="innerLayout.panes.north.css('backgroundColor','')">    North Color = Default</a></li>
			<li><a href="#" onClick="alert('innerLayout.name = \''+innerLayout.options.name+'\'')">Show Layout Name</a></li>
			<li><a href="#" onClick="showOptions(innerLayout,'defaults')">Show Options.Defaults</a></li>
			<li><a href="#" onClick="showOptions(innerLayout,'north')">   Show Options.North</a></li>
			<li><a href="#" onClick="showOptions(innerLayout,'south')">   Show Options.South</a></li>
			<li><a href="#" onClick="showOptions(innerLayout,'west')">    Show Options.West</a></li>
			<li><a href="#" onClick="showOptions(innerLayout,'east')">    Show Options.East</a></li>
			<li><a href="#" onClick="showOptions(innerLayout,'center')">  Show Options.Center</a></li>
			<li><a href="#" onClick="showState(innerLayout,'container')"> Show State.Container</a></li>
			<li><a href="#" onClick="showState(innerLayout,'north')">     Show State.North</a></li>
			<li><a href="#" onClick="showState(innerLayout,'south')">     Show State.South</a></li>
			<li><a href="#" onClick="showState(innerLayout,'west')">      Show State.West</a></li>
			<li><a href="#" onClick="showState(innerLayout,'east')">      Show State.East</a></li>
			<li><a href="#" onClick="showState(innerLayout,'center')">    Show State.Center</a></li>
		</ul>
-->
	</div>

	<div class="footer">Status</div>

</div>

<SCRIPT type="text/javascript">
    	$(document).ready( function() {
                $("#accordion2").accordion({
                        heightStyle:    "fill"
		,	fillSpace:	true
		});
	});                
</SCRIPT>
    