<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>User Robot</title>
<link href="/css/style.css" rel="stylesheet" type="text/css" />
<script src="/js/html5.js" type="text/javascript"></script>
<meta name="google-site-verification" content="PbSWX8zh-D1nGYxZcFCTILLVJfJnQcak5j-DK30d3Do" />

<link rel="shortcut icon" href="/images/icon.ico" type="image/x-icon">
<link rel="icon" href="/images/icon.ico" type="image/x-icon">


<script type="text/javascript" src="/js/jquery.min.js" charset="utf-8"></script>

<link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet">
<script src="/bootstrap/js/bootstrap.min.js"></script>


</head>
<body>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-36079188-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

<div class="layout">
<div id="top"></div>
<!-- header starts -->
  <header id="sticky_nav">
    <div class="header-inner">
      <div class="logo npl"> <a href="/index"><img width="330" height="57" src="/images/logo.png" alt="logo" /></a></div>
      <div class="right-div">
            <?php
                if( $this->isLoggedIn  == 'true')
                    echo '<div class="sign-in"><a href="/login/logout">Logout</a></div>';
                else
                    echo '<div class="sign-in"><a href="/login/index">Sign In </a></div>';
            ?>
        <nav>
        
          <ul id="links">
            <li><a href="/contact/getstarted">Contact Us</a></li>
            <?php
                if( $this->isLoggedIn  == 'true')
                echo '<li><a href="/Dashboard"> Dashboard </a></li>';
            ?>
          </ul>
         
        </nav>
      </div>
    </div>
  </header>



<?php echo $this->layout()->content; ?>

<footer>
    <div class="footer-inner">
      <div class="footer-left">
        <p>&copy; Copyright 2013 USERrobot Inc. All Rights Reserved </p>
      </div>
    </div>
  </footer>
  <!-- footer ends -->
</div>
<script>

jQuery(document).ready(function($) {
 
    $(".scroll").click(function(event){         
        event.preventDefault();
        $('html,body').animate({scrollTop:$(this.hash).offset().top}, 500);
    });
});
</script>

<!-- begin olark code -->
<script data-cfasync="false" type='text/javascript'>/*<![CDATA[*/window.olark||(function(c){var f=window,d=document,l=f.location.protocol=="https:"?"https:":"http:",z=c.name,r="load";var nt=function(){
f[z]=function(){
(a.s=a.s||[]).push(arguments)};var a=f[z]._={
},q=c.methods.length;while(q--){(function(n){f[z][n]=function(){
f[z]("call",n,arguments)}})(c.methods[q])}a.l=c.loader;a.i=nt;a.p={
0:+new Date};a.P=function(u){
a.p[u]=new Date-a.p[0]};function s(){
a.P(r);f[z](r)}f.addEventListener?f.addEventListener(r,s,false):f.attachEvent("on"+r,s);var ld=function(){function p(hd){
hd="head";return["<",hd,"></",hd,"><",i,' onl' + 'oad="var d=',g,";d.getElementsByTagName('head')[0].",j,"(d.",h,"('script')).",k,"='",l,"//",a.l,"'",'"',"></",i,">"].join("")}var i="body",m=d[i];if(!m){
return setTimeout(ld,100)}a.P(1);var j="appendChild",h="createElement",k="src",n=d[h]("div"),v=n[j](d[h](z)),b=d[h]("iframe"),g="document",e="domain",o;n.style.display="none";m.insertBefore(n,m.firstChild).id=z;b.frameBorder="0";b.id=z+"-loader";if(/MSIE[ ]+6/.test(navigator.userAgent)){
b.src="javascript:false"}b.allowTransparency="true";v[j](b);try{
b.contentWindow[g].open()}catch(w){
c[e]=d[e];o="javascript:var d="+g+".open();d.domain='"+d.domain+"';";b[k]=o+"void(0);"}try{
var t=b.contentWindow[g];t.write(p());t.close()}catch(x){
b[k]=o+'d.write("'+p().replace(/"/g,String.fromCharCode(92)+'"')+'");d.close();'}a.P(2)};ld()};nt()})({
loader: "static.olark.com/jsclient/loader0.js",name:"olark",methods:["configure","extend","declare","identify"]});
/* custom configuration goes here (www.olark.com/documentation) */
olark.identify('8578-836-10-8741');/*]]>*/</script><noscript><a href="https://www.olark.com/site/8578-836-10-8741/contact" title="Contact us" target="_blank">Questions? Feedback?</a> powered by <a href="http://www.olark.com?welcome" title="Olark live chat software">Olark live chat software</a></noscript>
<!-- end olark code -->

</body>
</html>
