<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>User Robot</title>
<link href="/css/style.css" rel="stylesheet" type="text/css" />
<script src="/js/html5.js" type="text/javascript"></script>
<meta name="google-site-verification" content="PbSWX8zh-D1nGYxZcFCTILLVJfJnQcak5j-DK30d3Do" />

<link rel="shortcut icon" href="/images/icon.ico" type="image/x-icon">
<link rel="icon" href="/images/icon.ico" type="image/x-icon">


<script type="text/javascript" src="/js/jquery.min.js" charset="utf-8"></script>

<link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet">
<script src="/bootstrap/js/bootstrap.min.js"></script>


</head>
<body>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-36079188-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

<div class="layout">
<div id="top"></div>
<!-- header starts -->
  <header id="sticky_nav">
    <div class="header-inner">
      <div class="logo npl"> <a href="/index"><img width="330" height="57" src="/images/logo.png" alt="logo" /></a></div>
      <div class="right-div">
            <?php
                if( $this->isLoggedIn  == 'true')
                    echo '<div class="sign-in"><a href="/login/logout">Logout</a></div>';
                else
                    echo '<div class="sign-in"><a href="/login/index">Sign In </a></div>';
            ?>
        <nav>
        
          <ul id="links">
            <li><a href="/contact/getstarted">Get Started</a></li>
            <?php
                if( $this->isLoggedIn  == 'true')
                echo '<li><a href="/Dashboard"> Dashboard </a></li>';
            ?>
          </ul>
         
        </nav>
      </div>
    </div>
  </header>



<?php echo $this->layout()->content; ?>

<footer>
    <div class="footer-inner">
      <div class="footer-left">
        <p>&copy; Copyright 2013 USERrobot Inc. All Rights Reserved </p>
      </div>
    </div>
  </footer>
  <!-- footer ends -->
</div>
<script>

$(function() {
 
    // grab the initial top offset of the navigation 
    var sticky_nav_offset_top = $('#sticky_nav').offset().top;
     
    // our function that decides weather the navigation bar should have "fixed" css position or not.
    var sticky_nav = function(){
        var scroll_top = $(window).scrollTop(); // our current vertical position from the top
         
        // if we've scrolled more than the navigation, change its position to fixed to stick to top,
        // otherwise change it back to relative
        if (scroll_top > sticky_nav_offset_top) { 
            $('#sticky_nav').css({ 'position': 'fixed', 'top':0, 'left':0 });
        } else {
            $('#sticky_nav').css({ 'position': 'relative' ,'z-index':1000,'width':'100%'}); 
        }   
    };
     
    // run our function on load
    sticky_nav();
     
    // and run it again every time you scroll
    $(window).scroll(function() {
         sticky_nav();
    });
 
});

jQuery(document).ready(function($) {
 
    $(".scroll").click(function(event){         
        event.preventDefault();
        $('html,body').animate({scrollTop:$(this.hash).offset().top}, 500);
    });
});
</script>
</body>
</html>
